// Package catalogue constructs every implemented inspection in stable execution order.
package catalogue

import (
	"custos/internal/inspection/analysis"
	"custos/internal/inspection/rules/abstractclassinstantiation"
	"custos/internal/inspection/rules/accessmodifierpresented"
	"custos/internal/inspection/rules/aeadauthenticationtagdiscarded"
	"custos/internal/inspection/rules/aeaddecryptiontaglengthunchecked"
	"custos/internal/inspection/rules/aliasfunctionsusage"
	"custos/internal/inspection/rules/alterinforeach"
	"custos/internal/inspection/rules/ambiguousmethodscallsinarraymapping"
	"custos/internal/inspection/rules/ambiguousreplacementbackreference"
	"custos/internal/inspection/rules/appendmodeseekusedforoverwrite"
	"custos/internal/inspection/rules/argumentunpackingcanbeused"
	"custos/internal/inspection/rules/arraychunkinvalidsize"
	"custos/internal/inspection/rules/arraycolumnduplicateindexloss"
	"custos/internal/inspection/rules/arraycolumnmissingfield"
	"custos/internal/inspection/rules/arraycombinelengthmismatch"
	"custos/internal/inspection/rules/arraycopyretainsreferences"
	"custos/internal/inspection/rules/arraydiffonnestedarrays"
	"custos/internal/inspection/rules/arrayfillnegativecount"
	"custos/internal/inspection/rules/arrayfillsharesobject"
	"custos/internal/inspection/rules/arrayfilterdropszero"
	"custos/internal/inspection/rules/arrayflipduplicatevalueloss"
	"custos/internal/inspection/rules/arrayflipinvalidvaluetype"
	"custos/internal/inspection/rules/arrayislistcanbeused"
	"custos/internal/inspection/rules/arraymapmissingcallbackreturn"
	"custos/internal/inspection/rules/arraymergenumerickeyloss"
	"custos/internal/inspection/rules/arraymultisortlengthmismatch"
	"custos/internal/inspection/rules/arraypushmissuse"
	"custos/internal/inspection/rules/arrayrandinvalidcount"
	"custos/internal/inspection/rules/arrayrandkeyusedasvalue"
	"custos/internal/inspection/rules/arrayreducemissinginitialvalue"
	"custos/internal/inspection/rules/arraysearchusedasinarray"
	"custos/internal/inspection/rules/arrayslicediscardsrequiredkeys"
	"custos/internal/inspection/rules/arraysplicediscardsreplacementkeys"
	"custos/internal/inspection/rules/arrayuniondropsrightvalues"
	"custos/internal/inspection/rules/arrayuniquecanbeused"
	"custos/internal/inspection/rules/arrayuniqueonnonstringableobjects"
	"custos/internal/inspection/rules/arraywalkcallbackreturnignored"
	"custos/internal/inspection/rules/arrowfunctioncapturedcounter"
	"custos/internal/inspection/rules/assertioncontainsrequiredsideeffect"
	"custos/internal/inspection/rules/asyncsignalsetterreturnmisread"
	"custos/internal/inspection/rules/attributetargetmismatch"
	"custos/internal/inspection/rules/authenticationcookieallowsscriptaccess"
	"custos/internal/inspection/rules/autoloadingissues"
	"custos/internal/inspection/rules/backtickoperatorusage"
	"custos/internal/inspection/rules/badexceptionsprocessing"
	"custos/internal/inspection/rules/base64validationwithoutstrictmode"
	"custos/internal/inspection/rules/basicauthenticationoverplainhttp"
	"custos/internal/inspection/rules/bcmathexponentnotation"
	"custos/internal/inspection/rules/bcmathfloatoperand"
	"custos/internal/inspection/rules/bcmathscalediscardsrequiredfraction"
	"custos/internal/inspection/rules/bcryptpasswordtruncation"
	"custos/internal/inspection/rules/bufferedwriteflushedafterunlock"
	"custos/internal/inspection/rules/bytelengthusedascharactercount"
	"custos/internal/inspection/rules/bytepaddingusedforunicodewidth"
	"custos/internal/inspection/rules/callablemethodvalidity"
	"custos/internal/inspection/rules/callableparameterusecaseintypecontext"
	"custos/internal/inspection/rules/callbackrequiredargumentmismatch"
	"custos/internal/inspection/rules/cascadestringreplacement"
	"custos/internal/inspection/rules/cascadingdirnamecalls"
	"custos/internal/inspection/rules/caseinsensitivestringfunctionsmissuse"
	"custos/internal/inspection/rules/catchcannothandleknownthrowable"
	"custos/internal/inspection/rules/catchvariableoverwriteslocal"
	"custos/internal/inspection/rules/classconstantcanbeused"
	"custos/internal/inspection/rules/classconstantusagecorrectness"
	"custos/internal/inspection/rules/classmethodnamematchesfieldname"
	"custos/internal/inspection/rules/classmockingcorrectness"
	"custos/internal/inspection/rules/classoverridesfieldofsuperclass"
	"custos/internal/inspection/rules/classreimplementsparentinterface"
	"custos/internal/inspection/rules/closurecapturedvaluewrite"
	"custos/internal/inspection/rules/codepointslicesplitsgrapheme"
	"custos/internal/inspection/rules/collatorcomparisontruthinessreversed"
	"custos/internal/inspection/rules/collatorsortdiscardsrequiredkeys"
	"custos/internal/inspection/rules/compactarguments"
	"custos/internal/inspection/rules/compactcanbeused"
	"custos/internal/inspection/rules/comparisonoperandsorder"
	"custos/internal/inspection/rules/compressiondecoderformatmismatch"
	"custos/internal/inspection/rules/compressionleveloutsidesupportedrange"
	"custos/internal/inspection/rules/conflictingcontentlengthheaders"
	"custos/internal/inspection/rules/connecttimeoutassumedtoboundreads"
	"custos/internal/inspection/rules/constantcanbeused"
	"custos/internal/inspection/rules/contentdispositionfilenameneedsquoting"
	"custos/internal/inspection/rules/contentencodingbodymismatch"
	"custos/internal/inspection/rules/contentlengthknownbodymismatch"
	"custos/internal/inspection/rules/contentlengthusescharactercount"
	"custos/internal/inspection/rules/contentrangelengthmismatch"
	"custos/internal/inspection/rules/cookiedeletionscopemismatch"
	"custos/internal/inspection/rules/copyfailurereportedassuccess"
	"custos/internal/inspection/rules/corsoriginlistinvalid"
	"custos/internal/inspection/rules/corssubdomainwildcardinvalid"
	"custos/internal/inspection/rules/credentialedcorsuseswildcardorigin"
	"custos/internal/inspection/rules/cryptographicallysecurealgorithms"
	"custos/internal/inspection/rules/cryptographicallysecurerandomness"
	"custos/internal/inspection/rules/csvblankrecordshapemismatch"
	"custos/internal/inspection/rules/csvdelimiterinvalidbytelength"
	"custos/internal/inspection/rules/csvescapedefaultdependency"
	"custos/internal/inspection/rules/csvreadlengthsplitsknownrecord"
	"custos/internal/inspection/rules/ctypeintegerinterpretedascharactercode"
	"custos/internal/inspection/rules/curlcustomgetretainspostbody"
	"custos/internal/inspection/rules/curlcustomheadwithoutnobody"
	"custos/internal/inspection/rules/curlexplicitinfinitetimeout"
	"custos/internal/inspection/rules/curlheadercallbackmissingbytecount"
	"custos/internal/inspection/rules/curlheaderlistoverwritten"
	"custos/internal/inspection/rules/curlheaderoptionrequiresarray"
	"custos/internal/inspection/rules/curlheadersincludedindecodedbody"
	"custos/internal/inspection/rules/curlmethodoptionorderconflict"
	"custos/internal/inspection/rules/curlmultipartbodywithjsoncontenttype"
	"custos/internal/inspection/rules/curlmultisuccessassumedpertransfer"
	"custos/internal/inspection/rules/curlreadcallbackexceedsrequestedsize"
	"custos/internal/inspection/rules/curlredirectforwardscredentials"
	"custos/internal/inspection/rules/curlresponsebodywithoutreturntransfer"
	"custos/internal/inspection/rules/curlresponsezerorejected"
	"custos/internal/inspection/rules/curlsslserverspoofing"
	"custos/internal/inspection/rules/curltransportsuccessashttpsuccess"
	"custos/internal/inspection/rules/curluploaddeclaredsizemismatch"
	"custos/internal/inspection/rules/curlwholeurlescapedascomponent"
	"custos/internal/inspection/rules/curlwritecallbackmissingbytecount"
	"custos/internal/inspection/rules/dateintervalspecification"
	"custos/internal/inspection/rules/datelasterrorsfalseunchecked"
	"custos/internal/inspection/rules/dateminutesmonthtokenconfusion"
	"custos/internal/inspection/rules/dateonlyparseretainscurrenttime"
	"custos/internal/inspection/rules/dateparsenormalizationunchecked"
	"custos/internal/inspection/rules/datetimeconstantsusage"
	"custos/internal/inspection/rules/datetimesettimeusage"
	"custos/internal/inspection/rules/dateusage"
	"custos/internal/inspection/rules/decompressionfailureconsumed"
	"custos/internal/inspection/rules/decryptionfailureusedasplaintext"
	"custos/internal/inspection/rules/deflatestreamneverfinished"
	"custos/internal/inspection/rules/degradedswitch"
	"custos/internal/inspection/rules/deprecatedconstructorstyle"
	"custos/internal/inspection/rules/deprecatedinioptions"
	"custos/internal/inspection/rules/detachedsignaturepassedtocombinedverifier"
	"custos/internal/inspection/rules/directoryconstantcanbeused"
	"custos/internal/inspection/rules/directoryiteratordotentries"
	"custos/internal/inspection/rules/disallowwritingintostaticproperties"
	"custos/internal/inspection/rules/disconnectedforeachinstruction"
	"custos/internal/inspection/rules/domappendmovesnodeunexpectedly"
	"custos/internal/inspection/rules/domcrossdocumentappend"
	"custos/internal/inspection/rules/domelementvaluecontainsbareampersand"
	"custos/internal/inspection/rules/domlivenodelistremovalskipsnodes"
	"custos/internal/inspection/rules/dommissingattributecheckedasnull"
	"custos/internal/inspection/rules/domshallowimportdropsdescendants"
	"custos/internal/inspection/rules/domtextassignmentdestroyschildren"
	"custos/internal/inspection/rules/dstunsafecalendardayarithmetic"
	"custos/internal/inspection/rules/duplicatearraykeys"
	"custos/internal/inspection/rules/duplicatematchcondition"
	"custos/internal/inspection/rules/dynamiccallstoscopeintrospection"
	"custos/internal/inspection/rules/dynamiccorsoriginwithoutvary"
	"custos/internal/inspection/rules/dynamicinvocationviascoperesolution"
	"custos/internal/inspection/rules/efferentobjectcoupling"
	"custos/internal/inspection/rules/elvisoperatorcanbeused"
	"custos/internal/inspection/rules/emptyclass"
	"custos/internal/inspection/rules/emptysplcollectionextraction"
	"custos/internal/inspection/rules/encodingconversionargumentsreversed"
	"custos/internal/inspection/rules/encryptioninitializationvectorrandomness"
	"custos/internal/inspection/rules/enumfromuncheckedexternalvalue"
	"custos/internal/inspection/rules/enuminstantiation"
	"custos/internal/inspection/rules/exceptionconstructednotthrown"
	"custos/internal/inspection/rules/execoutputarrayaccumulates"
	"custos/internal/inspection/rules/exhaustedgeneratorreused"
	"custos/internal/inspection/rules/exitstatusreadwithoutnormalexitcheck"
	"custos/internal/inspection/rules/explodeemptyseparator"
	"custos/internal/inspection/rules/failedclosurebindinginvoked"
	"custos/internal/inspection/rules/fastdigestusedforpasswordstorage"
	"custos/internal/inspection/rules/fiberresumebeforestart"
	"custos/internal/inspection/rules/fiberresumedaftertermination"
	"custos/internal/inspection/rules/fiberreturnbeforetermination"
	"custos/internal/inspection/rules/fiberstartedtwice"
	"custos/internal/inspection/rules/fibersuspendoutsidefiber"
	"custos/internal/inspection/rules/filelockfailureunchecked"
	"custos/internal/inspection/rules/filepermissionfailurepassespolicy"
	"custos/internal/inspection/rules/filereadfailureunchecked"
	"custos/internal/inspection/rules/filestatcacheafterexternalmutation"
	"custos/internal/inspection/rules/filetruncatedbeforelock"
	"custos/internal/inspection/rules/filewriteresultunchecked"
	"custos/internal/inspection/rules/filteredlistjsonshape"
	"custos/internal/inspection/rules/finallythrowmasksexception"
	"custos/internal/inspection/rules/fixedtimestartwith"
	"custos/internal/inspection/rules/fopenbinaryunsafeusage"
	"custos/internal/inspection/rules/foreachinvariants"
	"custos/internal/inspection/rules/foreachreferencesurvivesloop"
	"custos/internal/inspection/rules/forgottendebugoutput"
	"custos/internal/inspection/rules/forkchildfallsintoparentwork"
	"custos/internal/inspection/rules/forkfailuretreatedasparent"
	"custos/internal/inspection/rules/formencodingusedforrfc3986signature"
	"custos/internal/inspection/rules/fractionalarraykeytruncation"
	"custos/internal/inspection/rules/fractionalmodulooperand"
	"custos/internal/inspection/rules/ftppendingtransferacceptedascomplete"
	"custos/internal/inspection/rules/gdalphaoutsidesupportedrange"
	"custos/internal/inspection/rules/gdcolorzerorejectedasfailure"
	"custos/internal/inspection/rules/gdimagedimensionsnotpositive"
	"custos/internal/inspection/rules/gdjpegqualityoutsidesupportedrange"
	"custos/internal/inspection/rules/gdpaletteindexdecodedasrgb"
	"custos/internal/inspection/rules/gdpngcompressionoutsidesupportedrange"
	"custos/internal/inspection/rules/gdtransformationresultignored"
	"custos/internal/inspection/rules/generatorcallneverconsumed"
	"custos/internal/inspection/rules/generatorreturnbeforecompletion"
	"custos/internal/inspection/rules/generatorrewindafteradvance"
	"custos/internal/inspection/rules/getclassusage"
	"custos/internal/inspection/rules/getdebugtypecanbeused"
	"custos/internal/inspection/rules/gettypemissuse"
	"custos/internal/inspection/rules/globbraceexpansionmissingflag"
	"custos/internal/inspection/rules/globfailureunchecked"
	"custos/internal/inspection/rules/gmpautomaticbasechangesdecimalinput"
	"custos/internal/inspection/rules/gmpdivisionbyknownzero"
	"custos/internal/inspection/rules/gmpdivisionpairusedasnumber"
	"custos/internal/inspection/rules/hardcodedcredentialatknownsink"
	"custos/internal/inspection/rules/hashcontextusedafterfinalization"
	"custos/internal/inspection/rules/hashfilefailureusedasdigest"
	"custos/internal/inspection/rules/headersaftercommittedoutput"
	"custos/internal/inspection/rules/heapiterationconsumescollection"
	"custos/internal/inspection/rules/hexdecodeoddlengthliteral"
	"custos/internal/inspection/rules/hostcookieprefixcontractviolation"
	"custos/internal/inspection/rules/hostnamesubstitution"
	"custos/internal/inspection/rules/httperrorbodyreadwithoutignoreerrors"
	"custos/internal/inspection/rules/ifreturnreturnsimplification"
	"custos/internal/inspection/rules/imagedecodefailureunchecked"
	"custos/internal/inspection/rules/imageencodercontenttypemismatch"
	"custos/internal/inspection/rules/imagickframeindexpastend"
	"custos/internal/inspection/rules/imagickresizestatususedasimage"
	"custos/internal/inspection/rules/imagicksingleblobdropsrequiredframes"
	"custos/internal/inspection/rules/immutabledateresultignored"
	"custos/internal/inspection/rules/implodeargumentsorder"
	"custos/internal/inspection/rules/inarraymissuse"
	"custos/internal/inspection/rules/incorrectrandomrange"
	"custos/internal/inspection/rules/incrementalinflateencodingmismatch"
	"custos/internal/inspection/rules/incrementdecrementoperationequivalent"
	"custos/internal/inspection/rules/infinityloop"
	"custos/internal/inspection/rules/instanceofcanbeused"
	"custos/internal/inspection/rules/intdivminimumintegeroverflow"
	"custos/internal/inspection/rules/intdivzerodivisor"
	"custos/internal/inspection/rules/integercastoutofrangeliteral"
	"custos/internal/inspection/rules/interfaceinstantiation"
	"custos/internal/inspection/rules/intervaldaycomponentastotal"
	"custos/internal/inspection/rules/intlcalendarsecondspassedasmilliseconds"
	"custos/internal/inspection/rules/intlformattingfailureunchecked"
	"custos/internal/inspection/rules/intlgregorianmonthoffbyone"
	"custos/internal/inspection/rules/intltimezoneoffsetmillisecondsusedasseconds"
	"custos/internal/inspection/rules/intltwelvehourfieldusedfortwentyfourhourtime"
	"custos/internal/inspection/rules/inversetriginvalidrealdomain"
	"custos/internal/inspection/rules/invertedifelseconstructs"
	"custos/internal/inspection/rules/iscountablecanbeused"
	"custos/internal/inspection/rules/isemptyfunctionusage"
	"custos/internal/inspection/rules/isiterablecanbeused"
	"custos/internal/inspection/rules/isnullfunctionusage"
	"custos/internal/inspection/rules/isoweekcalendaryearmismatch"
	"custos/internal/inspection/rules/issetargumentexistence"
	"custos/internal/inspection/rules/issetconstructscanbemerged"
	"custos/internal/inspection/rules/iteratorcountchangesrequiredposition"
	"custos/internal/inspection/rules/iteratormaterializationkeycollision"
	"custos/internal/inspection/rules/jsondecodeknowninvalidutf8"
	"custos/internal/inspection/rules/jsonencodeflagpassedtodecode"
	"custos/internal/inspection/rules/jsonencodeknownrecursivevalue"
	"custos/internal/inspection/rules/jsonencodenonfinitenumber"
	"custos/internal/inspection/rules/jsonencodingapiusage"
	"custos/internal/inspection/rules/jsonforceobjectchangesnestedlists"
	"custos/internal/inspection/rules/jsonintegerprecisionloss"
	"custos/internal/inspection/rules/jsoninvaliddepth"
	"custos/internal/inspection/rules/jsonnumericcheckchangesidentifiers"
	"custos/internal/inspection/rules/jsonpartialoutputoverridesthrow"
	"custos/internal/inspection/rules/libxmlerrorbuffernevercleared"
	"custos/internal/inspection/rules/linkedlistdeleteiterationunexpected"
	"custos/internal/inspection/rules/localizednumbertrailinginputaccepted"
	"custos/internal/inspection/rules/logarithminvalidrealdomain"
	"custos/internal/inspection/rules/longinheritancechain"
	"custos/internal/inspection/rules/loopclosurecapturesreference"
	"custos/internal/inspection/rules/loopwhichdoesnotloop"
	"custos/internal/inspection/rules/magicmethodsvalidity"
	"custos/internal/inspection/rules/millisecondsusedasunixseconds"
	"custos/internal/inspection/rules/misorderedmodifiers"
	"custos/internal/inspection/rules/missingarrayinitialization"
	"custos/internal/inspection/rules/missingissetimplementation"
	"custos/internal/inspection/rules/missingoremptygroupstatement"
	"custos/internal/inspection/rules/missusingparentkeyword"
	"custos/internal/inspection/rules/mkdirracecondition"
	"custos/internal/inspection/rules/mktimeusage"
	"custos/internal/inspection/rules/mockingmethodscorrectness"
	"custos/internal/inspection/rules/monthadditiondateoverflow"
	"custos/internal/inspection/rules/multiassignmentusage"
	"custos/internal/inspection/rules/multibytepositionusedasbyteoffset"
	"custos/internal/inspection/rules/multiplereturnstatements"
	"custos/internal/inspection/rules/mysqlddlimplicitlycommitstransaction"
	"custos/internal/inspection/rules/mysqlibindingtypecountmismatch"
	"custos/internal/inspection/rules/mysqliboundarrayreassigned"
	"custos/internal/inspection/rules/mysqliescapedvaluesurvivescharsetchange"
	"custos/internal/inspection/rules/mysqliinvalidbindingtype"
	"custos/internal/inspection/rules/mysqlimultiqueryresultsnotdrained"
	"custos/internal/inspection/rules/mysqliplaceholderbindingmismatch"
	"custos/internal/inspection/rules/mysqliunbufferedresultblocksnextquery"
	"custos/internal/inspection/rules/nancheckedwithequality"
	"custos/internal/inspection/rules/negativebitshiftcount"
	"custos/internal/inspection/rules/nestedassignmentsusage"
	"custos/internal/inspection/rules/nestednotoperators"
	"custos/internal/inspection/rules/nestedpdotransactionwithoutsavepoint"
	"custos/internal/inspection/rules/nestedpositiveifstatements"
	"custos/internal/inspection/rules/nestedternaryoperator"
	"custos/internal/inspection/rules/neverfunctionfallsthrough"
	"custos/internal/inspection/rules/nocontentresponsewithbody"
	"custos/internal/inspection/rules/nonblockingemptyreadtreatedaseof"
	"custos/internal/inspection/rules/nonblockingsocketconnectpendingrejected"
	"custos/internal/inspection/rules/nonblockingwaitzerotreatedasreaped"
	"custos/internal/inspection/rules/nonexhaustiveenummatch"
	"custos/internal/inspection/rules/nonrepeatableattributerepeated"
	"custos/internal/inspection/rules/nonsecureparsestrusage"
	"custos/internal/inspection/rules/nonsecureuniqidusage"
	"custos/internal/inspection/rules/nonvoidfunctionfallsthrough"
	"custos/internal/inspection/rules/notoptimalifconditions"
	"custos/internal/inspection/rules/notoptimalregularexpressions"
	"custos/internal/inspection/rules/nullcoalescingoperatorcanbeused"
	"custos/internal/inspection/rules/nullpointerexception"
	"custos/internal/inspection/rules/numberparseusescurrencytype"
	"custos/internal/inspection/rules/obgetcleancanbeused"
	"custos/internal/inspection/rules/offsetoperations"
	"custos/internal/inspection/rules/onetimeusevariables"
	"custos/internal/inspection/rules/onlywritesonparameter"
	"custos/internal/inspection/rules/opassignshortsyntax"
	"custos/internal/inspection/rules/opensslencryptionstatususedasciphertext"
	"custos/internal/inspection/rules/opensslkeylengthmismatch"
	"custos/internal/inspection/rules/opensslrawciphertextoptionmismatch"
	"custos/internal/inspection/rules/opensslsigningfailureignored"
	"custos/internal/inspection/rules/opensslverifytruthyresult"
	"custos/internal/inspection/rules/optionalregexcapturereadwithoutnullflag"
	"custos/internal/inspection/rules/overrideattributewithouttarget"
	"custos/internal/inspection/rules/ownedstreamnotclosed"
	"custos/internal/inspection/rules/packedhashtableoptimization"
	"custos/internal/inspection/rules/packformatargumentmismatch"
	"custos/internal/inspection/rules/parameterdefaultvalueisnotnull"
	"custos/internal/inspection/rules/parsedqueryvaluedecodedtwice"
	"custos/internal/inspection/rules/parsestrkeynormalizationmismatch"
	"custos/internal/inspection/rules/parseurlfailuredereferenced"
	"custos/internal/inspection/rules/partialstreamwriteunchecked"
	"custos/internal/inspection/rules/passingbyreferencecorrectness"
	"custos/internal/inspection/rules/passwordcomparedwithfreshhash"
	"custos/internal/inspection/rules/passworduseddirectlyasencryptionkey"
	"custos/internal/inspection/rules/passwordverifyargumentsreversed"
	"custos/internal/inspection/rules/pathcontainmentprefixboundary"
	"custos/internal/inspection/rules/pdoapiusage"
	"custos/internal/inspection/rules/pdoarrayboundtosingleplaceholder"
	"custos/internal/inspection/rules/pdoboundvalueassumedlive"
	"custos/internal/inspection/rules/pdoexecutearrayreplacesbindings"
	"custos/internal/inspection/rules/pdoexeczerorejectedasfailure"
	"custos/internal/inspection/rules/pdofetchbothleaksduplicatecolumns"
	"custos/internal/inspection/rules/pdofetchcolumnfalsyvalueloss"
	"custos/internal/inspection/rules/pdofetchintoretainssharedrows"
	"custos/internal/inspection/rules/pdogroupedfetchreadsremovedcolumn"
	"custos/internal/inspection/rules/pdoidentifierplaceholder"
	"custos/internal/inspection/rules/pdomixedplaceholderstyles"
	"custos/internal/inspection/rules/pdoplaceholderbindingmismatch"
	"custos/internal/inspection/rules/pdoquotedplaceholder"
	"custos/internal/inspection/rules/pdoreferencebindingvariablereuse"
	"custos/internal/inspection/rules/pdorepeatednamedmarkerwithoutemulation"
	"custos/internal/inspection/rules/pdoselectrowcountassumption"
	"custos/internal/inspection/rules/permissionmodewrittenindecimal"
	"custos/internal/inspection/rules/pgasyncdispatchassumedquerysuccess"
	"custos/internal/inspection/rules/pgasyncresultsnotdrained"
	"custos/internal/inspection/rules/pgescapedliteralquotedagain"
	"custos/internal/inspection/rules/pgfetchedzerorejected"
	"custos/internal/inspection/rules/pgidentifierescapedasliteral"
	"custos/internal/inspection/rules/pgreturnedrowsusedasaffectedrows"
	"custos/internal/inspection/rules/phpunitdeprecations"
	"custos/internal/inspection/rules/phpunittests"
	"custos/internal/inspection/rules/posixaccountlookupfailuredereferenced"
	"custos/internal/inspection/rules/potentialmalware"
	"custos/internal/inspection/rules/poweroperatorcanbeused"
	"custos/internal/inspection/rules/pregmatchalllayoutmismatch"
	"custos/internal/inspection/rules/pregmatchfailureasnonmatch"
	"custos/internal/inspection/rules/pregquoteusage"
	"custos/internal/inspection/rules/pregquoteusedonreplacement"
	"custos/internal/inspection/rules/pregreplacefailureunchecked"
	"custos/internal/inspection/rules/pregsplitcaptureflagwithoutgroups"
	"custos/internal/inspection/rules/preloadingusagecorrectness"
	"custos/internal/inspection/rules/printfscanfarguments"
	"custos/internal/inspection/rules/priorityqueueextractionshapemismatch"
	"custos/internal/inspection/rules/priorityqueueminorderassumption"
	"custos/internal/inspection/rules/processclosedbeforeownedpipes"
	"custos/internal/inspection/rules/processexecfailurereportedassuccess"
	"custos/internal/inspection/rules/processexitcodelostbyrepeatedstatusread"
	"custos/internal/inspection/rules/processpipedirectionmisinterpreted"
	"custos/internal/inspection/rules/processpipesdrainedsequentially"
	"custos/internal/inspection/rules/propernullcoalescingoperatorusage"
	"custos/internal/inspection/rules/propertycanbestatic"
	"custos/internal/inspection/rules/propertyinitializationflaws"
	"custos/internal/inspection/rules/randomapimigration"
	"custos/internal/inspection/rules/rangezerostep"
	"custos/internal/inspection/rules/readdirfalsyfilenameloss"
	"custos/internal/inspection/rules/readfromwriteonlystream"
	"custos/internal/inspection/rules/readloopprocesseseoffailure"
	"custos/internal/inspection/rules/readmodifywritelocktoolate"
	"custos/internal/inspection/rules/readonlypropertyreassignment"
	"custos/internal/inspection/rules/realpathfailureusedaspath"
	"custos/internal/inspection/rules/realpathinstreamcontext"
	"custos/internal/inspection/rules/recursivereplaceretainslisttail"
	"custos/internal/inspection/rules/recursivetraversalomitsdirectories"
	"custos/internal/inspection/rules/redirectcontinuesprotectedexecution"
	"custos/internal/inspection/rules/redundantelseclause"
	"custos/internal/inspection/rules/referencingobjects"
	"custos/internal/inspection/rules/reflectioncompositetypeassumednamed"
	"custos/internal/inspection/rules/reflectionnamedargumentmismatch"
	"custos/internal/inspection/rules/regexbodydoesnotcompile"
	"custos/internal/inspection/rules/regexbyteoffsetascharacteroffset"
	"custos/internal/inspection/rules/regexreplacementcallbackfallsthrough"
	"custos/internal/inspection/rules/regexreplacementreferencesmissinggroup"
	"custos/internal/inspection/rules/regexutf8subjectknowninvalid"
	"custos/internal/inspection/rules/relativesymlinktargetuseswrongbase"
	"custos/internal/inspection/rules/renamefailureunchecked"
	"custos/internal/inspection/rules/repeatedcookieheaderreplacement"
	"custos/internal/inspection/rules/repeatedhtmlentityencoding"
	"custos/internal/inspection/rules/requestcontrolledsessionid"
	"custos/internal/inspection/rules/returntypecanbedeclared"
	"custos/internal/inspection/rules/samesitenonewithoutsecure"
	"custos/internal/inspection/rules/scandirfailureiterated"
	"custos/internal/inspection/rules/secretstreampushafterfinaltag"
	"custos/internal/inspection/rules/securityadvisories"
	"custos/internal/inspection/rules/seeksuccesscheckedastruthy"
	"custos/internal/inspection/rules/selectfailuretreatedasreadiness"
	"custos/internal/inspection/rules/selectwatcharraysnotrestored"
	"custos/internal/inspection/rules/selfclassreferencing"
	"custos/internal/inspection/rules/semaphorefailureenterscriticalsection"
	"custos/internal/inspection/rules/senselessmethodduplication"
	"custos/internal/inspection/rules/senselessproxymethod"
	"custos/internal/inspection/rules/senselessternaryoperator"
	"custos/internal/inspection/rules/sessioncookieoptionssetafterstart"
	"custos/internal/inspection/rules/sessiondestroyleaveslocalauthentication"
	"custos/internal/inspection/rules/sessionlockheldduringblockingcall"
	"custos/internal/inspection/rules/sessionmutationafterclose"
	"custos/internal/inspection/rules/sessionnamechangedwhileactive"
	"custos/internal/inspection/rules/sessionregenerationfailureunchecked"
	"custos/internal/inspection/rules/shallowclonenestedmutation"
	"custos/internal/inspection/rules/sharedlockusedforwriting"
	"custos/internal/inspection/rules/sharedmemorywritecapacityexceeded"
	"custos/internal/inspection/rules/shortechotagcanbeused"
	"custos/internal/inspection/rules/shortlistsyntaxcanbeused"
	"custos/internal/inspection/rules/shortopentagusage"
	"custos/internal/inspection/rules/shortstreamreadunchecked"
	"custos/internal/inspection/rules/signalhandlerhasnodispatchmechanism"
	"custos/internal/inspection/rules/signalregistrationfailurereportedassuccess"
	"custos/internal/inspection/rules/signalwaitfailureacceptedassignal"
	"custos/internal/inspection/rules/simplexmlchildvaluecontainsbareampersand"
	"custos/internal/inspection/rules/simplexmlloadfileusage"
	"custos/internal/inspection/rules/simplexmlmissingnodecheckedasnull"
	"custos/internal/inspection/rules/simplexmltextcastasboolean"
	"custos/internal/inspection/rules/slowarrayoperationsinloop"
	"custos/internal/inspection/rules/soaplastrequestwithouttracing"
	"custos/internal/inspection/rules/soapnonwsdlrequiredoptionsmissing"
	"custos/internal/inspection/rules/socketreadzerorejected"
	"custos/internal/inspection/rules/sodiumkdfcontextlengthmismatch"
	"custos/internal/inspection/rules/sodiumnoncelengthmismatch"
	"custos/internal/inspection/rules/sodiumsecretboxkeylengthmismatch"
	"custos/internal/inspection/rules/sodiumsecretboxnoncereused"
	"custos/internal/inspection/rules/sortcomparatorreturnsboolean"
	"custos/internal/inspection/rules/sortcomparatorreturnsfloat"
	"custos/internal/inspection/rules/sortresultusedasarray"
	"custos/internal/inspection/rules/splfixedarrayindexoutofbounds"
	"custos/internal/inspection/rules/splfixedarrayshrinkdiscardsvalues"
	"custos/internal/inspection/rules/splobjectstorageindirectarraymutation"
	"custos/internal/inspection/rules/sqlitebindingindexzero"
	"custos/internal/inspection/rules/sqliteclearwithoutrequiredreset"
	"custos/internal/inspection/rules/sqlitefetchbothleaksduplicatecolumns"
	"custos/internal/inspection/rules/sqliteforeignkeysettinginsidetransaction"
	"custos/internal/inspection/rules/sqlitenondeterministicfunctiondeclareddeterministic"
	"custos/internal/inspection/rules/sqlitenullbindingdiscardsvalue"
	"custos/internal/inspection/rules/sqliteresultusedafterfinalize"
	"custos/internal/inspection/rules/sqlnullcomparedwithequality"
	"custos/internal/inspection/rules/staticclosurecanbeused"
	"custos/internal/inspection/rules/staticinvocationviathis"
	"custos/internal/inspection/rules/staticlambdabinding"
	"custos/internal/inspection/rules/strcontainscanbeused"
	"custos/internal/inspection/rules/streamopenfailureunchecked"
	"custos/internal/inspection/rules/streamoutputreturnusedascontent"
	"custos/internal/inspection/rules/streamuseafterclose"
	"custos/internal/inspection/rules/strendswithcanbeused"
	"custos/internal/inspection/rules/stringcasemanipulation"
	"custos/internal/inspection/rules/stringnormalization"
	"custos/internal/inspection/rules/stringoffsetwritetruncatesvalue"
	"custos/internal/inspection/rules/stringpademptypadding"
	"custos/internal/inspection/rules/stringrepeatnegativecount"
	"custos/internal/inspection/rules/stringsfirstcharacterscompare"
	"custos/internal/inspection/rules/strleninemptystringcheckcontext"
	"custos/internal/inspection/rules/strstartswithcanbeused"
	"custos/internal/inspection/rules/strstrusedasstrpos"
	"custos/internal/inspection/rules/strtokstateclobbered"
	"custos/internal/inspection/rules/strtotimeusage"
	"custos/internal/inspection/rules/strtrusageasstrreplace"
	"custos/internal/inspection/rules/substrshorthandusage"
	"custos/internal/inspection/rules/substrusedasarrayaccess"
	"custos/internal/inspection/rules/substrusedasstrpos"
	"custos/internal/inspection/rules/suspiciousassignments"
	"custos/internal/inspection/rules/suspiciousbinaryoperation"
	"custos/internal/inspection/rules/suspiciousfunctioncalls"
	"custos/internal/inspection/rules/suspiciousloop"
	"custos/internal/inspection/rules/suspiciousreturn"
	"custos/internal/inspection/rules/suspicioussemicolon"
	"custos/internal/inspection/rules/switchcontinuationinloop"
	"custos/internal/inspection/rules/sysvmessageexceedsreceivecapacity"
	"custos/internal/inspection/rules/sysvmessageserializationmismatch"
	"custos/internal/inspection/rules/tempnamdirectoryfallbackunchecked"
	"custos/internal/inspection/rules/ternaryoperatorsimplify"
	"custos/internal/inspection/rules/throwrawexception"
	"custos/internal/inspection/rules/tlshandshakependingaccepted"
	"custos/internal/inspection/rules/traitinstantiation"
	"custos/internal/inspection/rules/traitspropertiesconflicts"
	"custos/internal/inspection/rules/transactionearlyreturn"
	"custos/internal/inspection/rules/transactionexceptionwithoutrollback"
	"custos/internal/inspection/rules/transferencodingwithcontentlength"
	"custos/internal/inspection/rules/transliterationfailureconsumed"
	"custos/internal/inspection/rules/trimmaskusedassuffix"
	"custos/internal/inspection/rules/truncationassumedtorewind"
	"custos/internal/inspection/rules/typescastingcanbeused"
	"custos/internal/inspection/rules/typeunsafearraysearch"
	"custos/internal/inspection/rules/typeunsafecomparison"
	"custos/internal/inspection/rules/umasksetterreturnmisread"
	"custos/internal/inspection/rules/undeclareddynamicproperty"
	"custos/internal/inspection/rules/unescapedhtmloutput"
	"custos/internal/inspection/rules/unicodenormalizationfailureconsumed"
	"custos/internal/inspection/rules/uninitializedtypedpropertyread"
	"custos/internal/inspection/rules/unitenumjsonencoding"
	"custos/internal/inspection/rules/unknowninspection"
	"custos/internal/inspection/rules/unknownnamedargument"
	"custos/internal/inspection/rules/unlinkfailurereportedassuccess"
	"custos/internal/inspection/rules/unnecessaryassertion"
	"custos/internal/inspection/rules/unnecessarycasting"
	"custos/internal/inspection/rules/unnecessarydoublequotes"
	"custos/internal/inspection/rules/unnecessaryfinalmodifier"
	"custos/internal/inspection/rules/unnecessaryissetarguments"
	"custos/internal/inspection/rules/unnecessarysemicolon"
	"custos/internal/inspection/rules/unnecessaryusealias"
	"custos/internal/inspection/rules/unpackbuffertooshort"
	"custos/internal/inspection/rules/unpackednamedargumentcollision"
	"custos/internal/inspection/rules/unqualifiedreference"
	"custos/internal/inspection/rules/unreachablecatchclause"
	"custos/internal/inspection/rules/unsafeissetoverarray"
	"custos/internal/inspection/rules/unserializeexploits"
	"custos/internal/inspection/rules/unserializefalseambiguity"
	"custos/internal/inspection/rules/unsetconstructscanbemerged"
	"custos/internal/inspection/rules/unsupportedemptylistassignments"
	"custos/internal/inspection/rules/unsupportedstringoffsetoperations"
	"custos/internal/inspection/rules/untrustedfilesystempath"
	"custos/internal/inspection/rules/untrustedforwardedclientaddress"
	"custos/internal/inspection/rules/untrustedheadervalue"
	"custos/internal/inspection/rules/untrustedinclusion"
	"custos/internal/inspection/rules/untrustedldapfilter"
	"custos/internal/inspection/rules/untrustednetworkdestination"
	"custos/internal/inspection/rules/untrustedshellcommand"
	"custos/internal/inspection/rules/untrustedsqlconstruction"
	"custos/internal/inspection/rules/untrustedxmlexternalentityexpansion"
	"custos/internal/inspection/rules/untrustedxmlwriterrawcontent"
	"custos/internal/inspection/rules/unusedconstructordependencies"
	"custos/internal/inspection/rules/unusedgotolabel"
	"custos/internal/inspection/rules/unvalidatedredirecttarget"
	"custos/internal/inspection/rules/uploadclientmimetrusted"
	"custos/internal/inspection/rules/uselessreturn"
	"custos/internal/inspection/rules/uselessunset"
	"custos/internal/inspection/rules/usinginclusiononcereturnvalue"
	"custos/internal/inspection/rules/usinginclusionreturnvalue"
	"custos/internal/inspection/rules/usortdiscardsrequiredkeys"
	"custos/internal/inspection/rules/utf8bytetruncation"
	"custos/internal/inspection/rules/validatedbooleanfalserejectedasinvalid"
	"custos/internal/inspection/rules/validatedintegerzerorejected"
	"custos/internal/inspection/rules/variablefunctionsusage"
	"custos/internal/inspection/rules/varyheaderoverwritesearlierdimensions"
	"custos/internal/inspection/rules/waitstatususedasexitcode"
	"custos/internal/inspection/rules/weakmapvalueretainskey"
	"custos/internal/inspection/rules/worldwritablepermission"
	"custos/internal/inspection/rules/writetoreadonlystream"
	"custos/internal/inspection/rules/xmlparserneverreceivesfinalchunk"
	"custos/internal/inspection/rules/xmlparsezerocomparedwithfalse"
	"custos/internal/inspection/rules/xmlreaderattributecursornotrestored"
	"custos/internal/inspection/rules/xmlwriterattributeaftercontent"
	"custos/internal/inspection/rules/xmlwritermemoryoutputinurimode"
	"custos/internal/inspection/rules/xpathignoresdefaultnamespace"
	"custos/internal/inspection/rules/xpathqueryfailuredereferenced"
	"custos/internal/inspection/rules/xsltransformationfailureconsumed"
	"custos/internal/inspection/rules/zipclosefailureunchecked"
	"custos/internal/inspection/rules/zipentryindexpastend"
	"custos/internal/inspection/rules/zipentrynamecollision"
	"custos/internal/inspection/rules/zipentrystreamusedafterarchiveclose"
	"custos/internal/inspection/rules/zipextractionexceedsconfiguredbudget"
	"custos/internal/inspection/rules/zipfirstentrytreatedasmissing"
	"custos/internal/inspection/rules/zipopentruthyresult"
	"custos/internal/inspection/rules/zipsourceremovedbeforearchiveclose"
)

// All returns inspections in stable group and identifier order.
func All() []analysis.Rule {
	return []analysis.Rule{
		badexceptionsprocessing.New(),
		callableparameterusecaseintypecontext.New(),
		classoverridesfieldofsuperclass.New(),
		classreimplementsparentinterface.New(),
		efferentobjectcoupling.New(),
		emptyclass.New(),
		longinheritancechain.New(),
		multiplereturnstatements.New(),
		propertycanbestatic.New(),
		accessmodifierpresented.New(),
		comparisonoperandsorder.New(),
		disallowwritingintostaticproperties.New(),
		dynamicinvocationviascoperesolution.New(),
		implodeargumentsorder.New(),
		incrementdecrementoperationequivalent.New(),
		isemptyfunctionusage.New(),
		isnullfunctionusage.New(),
		misorderedmodifiers.New(),
		missusingparentkeyword.New(),
		missingoremptygroupstatement.New(),
		nestedassignmentsusage.New(),
		nestednotoperators.New(),
		nestedpositiveifstatements.New(),
		opassignshortsyntax.New(),
		parameterdefaultvalueisnotnull.New(),
		propernullcoalescingoperatorusage.New(),
		selfclassreferencing.New(),
		shortechotagcanbeused.New(),
		shortopentagusage.New(),
		staticclosurecanbeused.New(),
		staticinvocationviathis.New(),
		unnecessarydoublequotes.New(),
		unknowninspection.New(),
		unnecessarycasting.New(),
		unnecessaryfinalmodifier.New(),
		unnecessarysemicolon.New(),
		unnecessaryusealias.New(),
		unsetconstructscanbemerged.New(),
		usinginclusionreturnvalue.New(),
		deprecatedinioptions.New(),
		fopenbinaryunsafeusage.New(),
		mktimeusage.New(),
		randomapimigration.New(),
		classmethodnamematchesfieldname.New(),
		nestedternaryoperator.New(),
		referencingobjects.New(),
		senselessternaryoperator.New(),
		uselessreturn.New(),
		arraysearchusedasinarray.New(),
		arrayuniquecanbeused.New(),
		compactcanbeused.New(),
		degradedswitch.New(),
		disconnectedforeachinstruction.New(),
		foreachinvariants.New(),
		gettypemissuse.New(),
		ifreturnreturnsimplification.New(),
		invertedifelseconstructs.New(),
		issetconstructscanbemerged.New(),
		loopwhichdoesnotloop.New(),
		multiassignmentusage.New(),
		notoptimalifconditions.New(),
		obgetcleancanbeused.New(),
		onetimeusevariables.New(),
		pdoapiusage.New(),
		redundantelseclause.New(),
		strtrusageasstrreplace.New(),
		stringcasemanipulation.New(),
		stringnormalization.New(),
		strleninemptystringcheckcontext.New(),
		substrusedasstrpos.New(),
		ternaryoperatorsimplify.New(),
		throwrawexception.New(),
		unsafeissetoverarray.New(),
		aliasfunctionsusage.New(),
		argumentunpackingcanbeused.New(),
		arrayislistcanbeused.New(),
		cascadingdirnamecalls.New(),
		classconstantcanbeused.New(),
		constantcanbeused.New(),
		deprecatedconstructorstyle.New(),
		directoryconstantcanbeused.New(),
		dynamiccallstoscopeintrospection.New(),
		elvisoperatorcanbeused.New(),
		getclassusage.New(),
		getdebugtypecanbeused.New(),
		instanceofcanbeused.New(),
		iscountablecanbeused.New(),
		isiterablecanbeused.New(),
		nullcoalescingoperatorcanbeused.New(),
		poweroperatorcanbeused.New(),
		returntypecanbedeclared.New(),
		shortlistsyntaxcanbeused.New(),
		strcontainscanbeused.New(),
		strendswithcanbeused.New(),
		strstartswithcanbeused.New(),
		typescastingcanbeused.New(),
		unsupportedemptylistassignments.New(),
		unsupportedstringoffsetoperations.New(),
		alterinforeach.New(),
		ambiguousmethodscallsinarraymapping.New(),
		arraypushmissuse.New(),
		cascadestringreplacement.New(),
		caseinsensitivestringfunctionsmissuse.New(),
		fixedtimestartwith.New(),
		inarraymissuse.New(),
		notoptimalregularexpressions.New(),
		packedhashtableoptimization.New(),
		slowarrayoperationsinloop.New(),
		strstrusedasstrpos.New(),
		strtotimeusage.New(),
		substrshorthandusage.New(),
		substrusedasarrayaccess.New(),
		unqualifiedreference.New(),
		variablefunctionsusage.New(),
		mockingmethodscorrectness.New(),
		phpunitdeprecations.New(),
		phpunittests.New(),
		unnecessaryassertion.New(),
		abstractclassinstantiation.New(),
		ambiguousreplacementbackreference.New(),
		appendmodeseekusedforoverwrite.New(),
		arraychunkinvalidsize.New(),
		arraycolumnduplicateindexloss.New(),
		arraycolumnmissingfield.New(),
		arraycombinelengthmismatch.New(),
		arraycopyretainsreferences.New(),
		arraydiffonnestedarrays.New(),
		arrayfillnegativecount.New(),
		arrayfillsharesobject.New(),
		arrayfilterdropszero.New(),
		arrayflipduplicatevalueloss.New(),
		arrayflipinvalidvaluetype.New(),
		arraymapmissingcallbackreturn.New(),
		arraymergenumerickeyloss.New(),
		arraymultisortlengthmismatch.New(),
		arrayrandinvalidcount.New(),
		arrayrandkeyusedasvalue.New(),
		arrayreducemissinginitialvalue.New(),
		arrayslicediscardsrequiredkeys.New(),
		arraysplicediscardsreplacementkeys.New(),
		arrayuniondropsrightvalues.New(),
		arrayuniqueonnonstringableobjects.New(),
		arraywalkcallbackreturnignored.New(),
		arrowfunctioncapturedcounter.New(),
		assertioncontainsrequiredsideeffect.New(),
		asyncsignalsetterreturnmisread.New(),
		attributetargetmismatch.New(),
		autoloadingissues.New(),
		base64validationwithoutstrictmode.New(),
		bcmathexponentnotation.New(),
		bcmathfloatoperand.New(),
		bcmathscalediscardsrequiredfraction.New(),
		bufferedwriteflushedafterunlock.New(),
		bytelengthusedascharactercount.New(),
		bytepaddingusedforunicodewidth.New(),
		callablemethodvalidity.New(),
		callbackrequiredargumentmismatch.New(),
		catchcannothandleknownthrowable.New(),
		catchvariableoverwriteslocal.New(),
		classconstantusagecorrectness.New(),
		classmockingcorrectness.New(),
		closurecapturedvaluewrite.New(),
		codepointslicesplitsgrapheme.New(),
		collatorcomparisontruthinessreversed.New(),
		collatorsortdiscardsrequiredkeys.New(),
		compactarguments.New(),
		compressiondecoderformatmismatch.New(),
		compressionleveloutsidesupportedrange.New(),
		conflictingcontentlengthheaders.New(),
		connecttimeoutassumedtoboundreads.New(),
		contentdispositionfilenameneedsquoting.New(),
		contentencodingbodymismatch.New(),
		contentlengthknownbodymismatch.New(),
		contentlengthusescharactercount.New(),
		contentrangelengthmismatch.New(),
		cookiedeletionscopemismatch.New(),
		copyfailurereportedassuccess.New(),
		corsoriginlistinvalid.New(),
		corssubdomainwildcardinvalid.New(),
		csvblankrecordshapemismatch.New(),
		csvdelimiterinvalidbytelength.New(),
		csvescapedefaultdependency.New(),
		csvreadlengthsplitsknownrecord.New(),
		ctypeintegerinterpretedascharactercode.New(),
		curlcustomgetretainspostbody.New(),
		curlcustomheadwithoutnobody.New(),
		curlexplicitinfinitetimeout.New(),
		curlheadercallbackmissingbytecount.New(),
		curlheaderlistoverwritten.New(),
		curlheaderoptionrequiresarray.New(),
		curlheadersincludedindecodedbody.New(),
		curlmethodoptionorderconflict.New(),
		curlmultisuccessassumedpertransfer.New(),
		curlmultipartbodywithjsoncontenttype.New(),
		curlreadcallbackexceedsrequestedsize.New(),
		curlresponsebodywithoutreturntransfer.New(),
		curlresponsezerorejected.New(),
		curltransportsuccessashttpsuccess.New(),
		curluploaddeclaredsizemismatch.New(),
		curlwholeurlescapedascomponent.New(),
		curlwritecallbackmissingbytecount.New(),
		dateintervalspecification.New(),
		datelasterrorsfalseunchecked.New(),
		dateminutesmonthtokenconfusion.New(),
		dateonlyparseretainscurrenttime.New(),
		dateparsenormalizationunchecked.New(),
		datetimeconstantsusage.New(),
		datetimesettimeusage.New(),
		decompressionfailureconsumed.New(),
		deflatestreamneverfinished.New(),
		directoryiteratordotentries.New(),
		domappendmovesnodeunexpectedly.New(),
		domcrossdocumentappend.New(),
		domelementvaluecontainsbareampersand.New(),
		domlivenodelistremovalskipsnodes.New(),
		dommissingattributecheckedasnull.New(),
		domshallowimportdropsdescendants.New(),
		domtextassignmentdestroyschildren.New(),
		dstunsafecalendardayarithmetic.New(),
		duplicatearraykeys.New(),
		duplicatematchcondition.New(),
		dynamiccorsoriginwithoutvary.New(),
		emptysplcollectionextraction.New(),
		encodingconversionargumentsreversed.New(),
		enumfromuncheckedexternalvalue.New(),
		enuminstantiation.New(),
		exceptionconstructednotthrown.New(),
		execoutputarrayaccumulates.New(),
		exhaustedgeneratorreused.New(),
		exitstatusreadwithoutnormalexitcheck.New(),
		explodeemptyseparator.New(),
		failedclosurebindinginvoked.New(),
		fiberresumebeforestart.New(),
		fiberresumedaftertermination.New(),
		fiberreturnbeforetermination.New(),
		fiberstartedtwice.New(),
		fibersuspendoutsidefiber.New(),
		filelockfailureunchecked.New(),
		filepermissionfailurepassespolicy.New(),
		filereadfailureunchecked.New(),
		filestatcacheafterexternalmutation.New(),
		filetruncatedbeforelock.New(),
		filewriteresultunchecked.New(),
		filteredlistjsonshape.New(),
		finallythrowmasksexception.New(),
		foreachreferencesurvivesloop.New(),
		forgottendebugoutput.New(),
		forkchildfallsintoparentwork.New(),
		forkfailuretreatedasparent.New(),
		formencodingusedforrfc3986signature.New(),
		fractionalarraykeytruncation.New(),
		fractionalmodulooperand.New(),
		ftppendingtransferacceptedascomplete.New(),
		gdalphaoutsidesupportedrange.New(),
		gdcolorzerorejectedasfailure.New(),
		gdimagedimensionsnotpositive.New(),
		gdjpegqualityoutsidesupportedrange.New(),
		gdpaletteindexdecodedasrgb.New(),
		gdpngcompressionoutsidesupportedrange.New(),
		gdtransformationresultignored.New(),
		generatorcallneverconsumed.New(),
		generatorreturnbeforecompletion.New(),
		generatorrewindafteradvance.New(),
		globbraceexpansionmissingflag.New(),
		globfailureunchecked.New(),
		gmpautomaticbasechangesdecimalinput.New(),
		gmpdivisionbyknownzero.New(),
		gmpdivisionpairusedasnumber.New(),
		headersaftercommittedoutput.New(),
		heapiterationconsumescollection.New(),
		hexdecodeoddlengthliteral.New(),
		httperrorbodyreadwithoutignoreerrors.New(),
		imagedecodefailureunchecked.New(),
		imageencodercontenttypemismatch.New(),
		imagickframeindexpastend.New(),
		imagickresizestatususedasimage.New(),
		imagicksingleblobdropsrequiredframes.New(),
		immutabledateresultignored.New(),
		incorrectrandomrange.New(),
		incrementalinflateencodingmismatch.New(),
		infinityloop.New(),
		intdivminimumintegeroverflow.New(),
		intdivzerodivisor.New(),
		integercastoutofrangeliteral.New(),
		interfaceinstantiation.New(),
		intervaldaycomponentastotal.New(),
		intlcalendarsecondspassedasmilliseconds.New(),
		intlformattingfailureunchecked.New(),
		intlgregorianmonthoffbyone.New(),
		intltimezoneoffsetmillisecondsusedasseconds.New(),
		intltwelvehourfieldusedfortwentyfourhourtime.New(),
		inversetriginvalidrealdomain.New(),
		isoweekcalendaryearmismatch.New(),
		issetargumentexistence.New(),
		iteratorcountchangesrequiredposition.New(),
		iteratormaterializationkeycollision.New(),
		jsondecodeknowninvalidutf8.New(),
		jsonencodeflagpassedtodecode.New(),
		jsonencodeknownrecursivevalue.New(),
		jsonencodenonfinitenumber.New(),
		jsonforceobjectchangesnestedlists.New(),
		jsonintegerprecisionloss.New(),
		jsoninvaliddepth.New(),
		jsonnumericcheckchangesidentifiers.New(),
		jsonpartialoutputoverridesthrow.New(),
		libxmlerrorbuffernevercleared.New(),
		linkedlistdeleteiterationunexpected.New(),
		localizednumbertrailinginputaccepted.New(),
		logarithminvalidrealdomain.New(),
		loopclosurecapturesreference.New(),
		magicmethodsvalidity.New(),
		millisecondsusedasunixseconds.New(),
		missingarrayinitialization.New(),
		missingissetimplementation.New(),
		mkdirracecondition.New(),
		monthadditiondateoverflow.New(),
		multibytepositionusedasbyteoffset.New(),
		mysqlddlimplicitlycommitstransaction.New(),
		mysqlibindingtypecountmismatch.New(),
		mysqliboundarrayreassigned.New(),
		mysqliescapedvaluesurvivescharsetchange.New(),
		mysqliinvalidbindingtype.New(),
		mysqlimultiqueryresultsnotdrained.New(),
		mysqliplaceholderbindingmismatch.New(),
		mysqliunbufferedresultblocksnextquery.New(),
		nancheckedwithequality.New(),
		negativebitshiftcount.New(),
		nestedpdotransactionwithoutsavepoint.New(),
		neverfunctionfallsthrough.New(),
		nocontentresponsewithbody.New(),
		nonblockingemptyreadtreatedaseof.New(),
		nonexhaustiveenummatch.New(),
		nonrepeatableattributerepeated.New(),
		nonvoidfunctionfallsthrough.New(),
		nonblockingsocketconnectpendingrejected.New(),
		nonblockingwaitzerotreatedasreaped.New(),
		nullpointerexception.New(),
		numberparseusescurrencytype.New(),
		offsetoperations.New(),
		optionalregexcapturereadwithoutnullflag.New(),
		overrideattributewithouttarget.New(),
		ownedstreamnotclosed.New(),
		packformatargumentmismatch.New(),
		parsestrkeynormalizationmismatch.New(),
		parseurlfailuredereferenced.New(),
		parsedqueryvaluedecodedtwice.New(),
		partialstreamwriteunchecked.New(),
		passingbyreferencecorrectness.New(),
		pathcontainmentprefixboundary.New(),
		pdoarrayboundtosingleplaceholder.New(),
		pdoboundvalueassumedlive.New(),
		pdoexeczerorejectedasfailure.New(),
		pdoexecutearrayreplacesbindings.New(),
		pdofetchbothleaksduplicatecolumns.New(),
		pdofetchcolumnfalsyvalueloss.New(),
		pdofetchintoretainssharedrows.New(),
		pdogroupedfetchreadsremovedcolumn.New(),
		pdoidentifierplaceholder.New(),
		pdomixedplaceholderstyles.New(),
		pdoplaceholderbindingmismatch.New(),
		pdoquotedplaceholder.New(),
		pdoreferencebindingvariablereuse.New(),
		pdorepeatednamedmarkerwithoutemulation.New(),
		pdoselectrowcountassumption.New(),
		permissionmodewrittenindecimal.New(),
		pgasyncdispatchassumedquerysuccess.New(),
		pgasyncresultsnotdrained.New(),
		pgescapedliteralquotedagain.New(),
		pgfetchedzerorejected.New(),
		pgidentifierescapedasliteral.New(),
		pgreturnedrowsusedasaffectedrows.New(),
		posixaccountlookupfailuredereferenced.New(),
		pregmatchalllayoutmismatch.New(),
		pregmatchfailureasnonmatch.New(),
		pregquoteusage.New(),
		pregquoteusedonreplacement.New(),
		pregreplacefailureunchecked.New(),
		pregsplitcaptureflagwithoutgroups.New(),
		preloadingusagecorrectness.New(),
		printfscanfarguments.New(),
		priorityqueueextractionshapemismatch.New(),
		priorityqueueminorderassumption.New(),
		processclosedbeforeownedpipes.New(),
		processexecfailurereportedassuccess.New(),
		processexitcodelostbyrepeatedstatusread.New(),
		processpipedirectionmisinterpreted.New(),
		processpipesdrainedsequentially.New(),
		rangezerostep.New(),
		readfromwriteonlystream.New(),
		readloopprocesseseoffailure.New(),
		readmodifywritelocktoolate.New(),
		readdirfalsyfilenameloss.New(),
		readonlypropertyreassignment.New(),
		realpathfailureusedaspath.New(),
		realpathinstreamcontext.New(),
		recursivereplaceretainslisttail.New(),
		recursivetraversalomitsdirectories.New(),
		redirectcontinuesprotectedexecution.New(),
		reflectioncompositetypeassumednamed.New(),
		reflectionnamedargumentmismatch.New(),
		regexbodydoesnotcompile.New(),
		regexbyteoffsetascharacteroffset.New(),
		regexreplacementcallbackfallsthrough.New(),
		regexreplacementreferencesmissinggroup.New(),
		regexutf8subjectknowninvalid.New(),
		relativesymlinktargetuseswrongbase.New(),
		renamefailureunchecked.New(),
		repeatedcookieheaderreplacement.New(),
		repeatedhtmlentityencoding.New(),
		samesitenonewithoutsecure.New(),
		scandirfailureiterated.New(),
		seeksuccesscheckedastruthy.New(),
		selectfailuretreatedasreadiness.New(),
		selectwatcharraysnotrestored.New(),
		semaphorefailureenterscriticalsection.New(),
		sessioncookieoptionssetafterstart.New(),
		sessiondestroyleaveslocalauthentication.New(),
		sessionlockheldduringblockingcall.New(),
		sessionmutationafterclose.New(),
		sessionnamechangedwhileactive.New(),
		shallowclonenestedmutation.New(),
		sharedlockusedforwriting.New(),
		sharedmemorywritecapacityexceeded.New(),
		shortstreamreadunchecked.New(),
		signalhandlerhasnodispatchmechanism.New(),
		signalregistrationfailurereportedassuccess.New(),
		signalwaitfailureacceptedassignal.New(),
		simplexmlchildvaluecontainsbareampersand.New(),
		simplexmlloadfileusage.New(),
		simplexmlmissingnodecheckedasnull.New(),
		simplexmltextcastasboolean.New(),
		soaplastrequestwithouttracing.New(),
		soapnonwsdlrequiredoptionsmissing.New(),
		socketreadzerorejected.New(),
		sodiumnoncelengthmismatch.New(),
		sortcomparatorreturnsboolean.New(),
		sortcomparatorreturnsfloat.New(),
		sortresultusedasarray.New(),
		splfixedarrayindexoutofbounds.New(),
		splfixedarrayshrinkdiscardsvalues.New(),
		splobjectstorageindirectarraymutation.New(),
		sqlnullcomparedwithequality.New(),
		sqlitebindingindexzero.New(),
		sqliteclearwithoutrequiredreset.New(),
		sqlitefetchbothleaksduplicatecolumns.New(),
		sqliteforeignkeysettinginsidetransaction.New(),
		sqlitenondeterministicfunctiondeclareddeterministic.New(),
		sqlitenullbindingdiscardsvalue.New(),
		sqliteresultusedafterfinalize.New(),
		staticlambdabinding.New(),
		streamopenfailureunchecked.New(),
		streamoutputreturnusedascontent.New(),
		streamuseafterclose.New(),
		stringoffsetwritetruncatesvalue.New(),
		stringpademptypadding.New(),
		stringrepeatnegativecount.New(),
		stringsfirstcharacterscompare.New(),
		strtokstateclobbered.New(),
		suspiciousassignments.New(),
		suspiciousbinaryoperation.New(),
		suspiciousfunctioncalls.New(),
		suspiciousloop.New(),
		suspiciousreturn.New(),
		suspicioussemicolon.New(),
		switchcontinuationinloop.New(),
		sysvmessageexceedsreceivecapacity.New(),
		sysvmessageserializationmismatch.New(),
		tempnamdirectoryfallbackunchecked.New(),
		tlshandshakependingaccepted.New(),
		traitinstantiation.New(),
		traitspropertiesconflicts.New(),
		transactionearlyreturn.New(),
		transactionexceptionwithoutrollback.New(),
		transferencodingwithcontentlength.New(),
		transliterationfailureconsumed.New(),
		trimmaskusedassuffix.New(),
		truncationassumedtorewind.New(),
		umasksetterreturnmisread.New(),
		undeclareddynamicproperty.New(),
		unicodenormalizationfailureconsumed.New(),
		uninitializedtypedpropertyread.New(),
		unitenumjsonencoding.New(),
		unknownnamedargument.New(),
		unlinkfailurereportedassuccess.New(),
		unpackbuffertooshort.New(),
		unpackednamedargumentcollision.New(),
		unreachablecatchclause.New(),
		unserializefalseambiguity.New(),
		untrustedforwardedclientaddress.New(),
		usinginclusiononcereturnvalue.New(),
		usortdiscardsrequiredkeys.New(),
		utf8bytetruncation.New(),
		validatedbooleanfalserejectedasinvalid.New(),
		validatedintegerzerorejected.New(),
		varyheaderoverwritesearlierdimensions.New(),
		waitstatususedasexitcode.New(),
		weakmapvalueretainskey.New(),
		writetoreadonlystream.New(),
		xpathignoresdefaultnamespace.New(),
		xpathqueryfailuredereferenced.New(),
		xmlparsezerocomparedwithfalse.New(),
		xmlparserneverreceivesfinalchunk.New(),
		xmlreaderattributecursornotrestored.New(),
		xmlwriterattributeaftercontent.New(),
		xmlwritermemoryoutputinurimode.New(),
		xsltransformationfailureconsumed.New(),
		zipclosefailureunchecked.New(),
		zipentryindexpastend.New(),
		zipentrynamecollision.New(),
		zipentrystreamusedafterarchiveclose.New(),
		zipextractionexceedsconfiguredbudget.New(),
		zipfirstentrytreatedasmissing.New(),
		zipopentruthyresult.New(),
		zipsourceremovedbeforearchiveclose.New(),
		aeadauthenticationtagdiscarded.New(),
		aeaddecryptiontaglengthunchecked.New(),
		authenticationcookieallowsscriptaccess.New(),
		backtickoperatorusage.New(),
		basicauthenticationoverplainhttp.New(),
		bcryptpasswordtruncation.New(),
		credentialedcorsuseswildcardorigin.New(),
		cryptographicallysecurealgorithms.New(),
		cryptographicallysecurerandomness.New(),
		curlredirectforwardscredentials.New(),
		curlsslserverspoofing.New(),
		decryptionfailureusedasplaintext.New(),
		detachedsignaturepassedtocombinedverifier.New(),
		encryptioninitializationvectorrandomness.New(),
		fastdigestusedforpasswordstorage.New(),
		hardcodedcredentialatknownsink.New(),
		hashcontextusedafterfinalization.New(),
		hashfilefailureusedasdigest.New(),
		hostcookieprefixcontractviolation.New(),
		hostnamesubstitution.New(),
		nonsecureparsestrusage.New(),
		nonsecureuniqidusage.New(),
		opensslencryptionstatususedasciphertext.New(),
		opensslkeylengthmismatch.New(),
		opensslrawciphertextoptionmismatch.New(),
		opensslsigningfailureignored.New(),
		opensslverifytruthyresult.New(),
		passwordcomparedwithfreshhash.New(),
		passworduseddirectlyasencryptionkey.New(),
		passwordverifyargumentsreversed.New(),
		potentialmalware.New(),
		requestcontrolledsessionid.New(),
		secretstreampushafterfinaltag.New(),
		securityadvisories.New(),
		sessionregenerationfailureunchecked.New(),
		sodiumkdfcontextlengthmismatch.New(),
		sodiumsecretboxkeylengthmismatch.New(),
		sodiumsecretboxnoncereused.New(),
		unescapedhtmloutput.New(),
		unserializeexploits.New(),
		untrustedfilesystempath.New(),
		untrustedheadervalue.New(),
		untrustedinclusion.New(),
		untrustedldapfilter.New(),
		untrustednetworkdestination.New(),
		untrustedshellcommand.New(),
		untrustedsqlconstruction.New(),
		untrustedxmlexternalentityexpansion.New(),
		untrustedxmlwriterrawcontent.New(),
		unvalidatedredirecttarget.New(),
		uploadclientmimetrusted.New(),
		worldwritablepermission.New(),
		jsonencodingapiusage.New(),
		typeunsafearraysearch.New(),
		typeunsafecomparison.New(),
		dateusage.New(),
		onlywritesonparameter.New(),
		propertyinitializationflaws.New(),
		senselessmethodduplication.New(),
		senselessproxymethod.New(),
		unnecessaryissetarguments.New(),
		unusedconstructordependencies.New(),
		unusedgotolabel.New(),
		uselessunset.New(),
	}
}
