package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRun(t *testing.T) {
	dir := t.TempDir()
	ast := filepath.Join(dir, "ast.go")
	kinds := filepath.Join(dir, "kinds.go")
	src := "package syntax\n\ntype Widget struct {\n\texprBase\n}\n\ntype Gadget struct{ stmtBase }\n\ntype plain struct{ n int }\n"
	if err := os.WriteFile(ast, []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}
	var stderr bytes.Buffer
	if code := run(ast, kinds, &stderr); code != 0 {
		t.Fatalf("exit %d: %s", code, stderr.String())
	}
	out, err := os.ReadFile(kinds)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"// Code generated by tools/genkinds from ast.go; DO NOT EDIT.",
		"KindInvalid NodeKind = iota\n\tKWidget\n\tKGadget\n\tNumNodeKinds",
		"func (*Widget) Kind() NodeKind { return KWidget }",
		"func (*Gadget) Kind() NodeKind { return KGadget }",
		`KWidget:     "Widget",`,
		`return "NodeKind(?)"`,
	} {
		if !strings.Contains(string(out), want) {
			t.Errorf("missing %q in:\n%s", want, out)
		}
	}
	if strings.Contains(string(out), "plain") {
		t.Errorf("non-node struct listed:\n%s", out)
	}
}

func TestRunErrors(t *testing.T) {
	dir := t.TempDir()
	// Missing input.
	var stderr bytes.Buffer
	if code := run(filepath.Join(dir, "none.go"), filepath.Join(dir, "k.go"), &stderr); code != 1 || !strings.HasPrefix(stderr.String(), "genkinds: ") {
		t.Fatalf("missing input: exit %d, %q", code, stderr.String())
	}
	// A type name that is not a valid identifier makes the output unformattable.
	bad := filepath.Join(dir, "bad.go")
	if err := os.WriteFile(bad, []byte("type 9Bad struct { exprBase }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	stderr.Reset()
	if code := run(bad, filepath.Join(dir, "k.go"), &stderr); code != 1 {
		t.Fatalf("bad name: exit %d", code)
	}
	// Unwritable output (a directory).
	good := filepath.Join(dir, "good.go")
	if err := os.WriteFile(good, []byte("type Ok struct { exprBase }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if code := run(good, dir, &stderr); code != 1 {
		t.Fatalf("unwritable output: exit %d", code)
	}
}
