// Command genkinds regenerates internal/syntax/kinds.go from the node types
// declared in internal/syntax/ast.go (run via `go generate ./internal/syntax`).
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"regexp"
)

var nodeRe = regexp.MustCompile(`type (\w+) struct\s*\{\s*(?:exprBase|stmtBase)`)

func main() {
	src, err := os.ReadFile("ast.go")
	if err != nil {
		fail(err)
	}
	var names []string
	for _, m := range nodeRe.FindAllSubmatch(src, -1) {
		names = append(names, string(m[1]))
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by tools/genkinds from ast.go; DO NOT EDIT.\n\npackage syntax\n\n")
	b.WriteString("// NodeKind identifies the concrete type of a node (used for rule dispatch).\ntype NodeKind uint8\n\nconst (\n\tKindInvalid NodeKind = iota\n")
	for _, n := range names {
		fmt.Fprintf(&b, "\tK%s\n", n)
	}
	b.WriteString("\tNumNodeKinds\n)\n\n")
	for _, n := range names {
		fmt.Fprintf(&b, "func (*%s) Kind() NodeKind { return K%s }\n", n, n)
	}
	b.WriteString("\nvar nodeKindNames = [...]string{\n\tKindInvalid: \"Invalid\",\n")
	for _, n := range names {
		fmt.Fprintf(&b, "\tK%s: %q,\n", n, n)
	}
	b.WriteString("}\n\nfunc (k NodeKind) String() string {\n\tif int(k) < len(nodeKindNames) {\n\t\treturn nodeKindNames[k]\n\t}\n\treturn \"NodeKind(?)\"\n}\n")
	out, err := format.Source(b.Bytes())
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile("kinds.go", out, 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "genkinds:", err)
	os.Exit(1)
}
