// Command genkinds regenerates internal/syntax/kinds.go from the node types
// declared in internal/syntax/ast.go (run via `go generate ./internal/syntax`).
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"os"
	"regexp"
)

var nodeRe = regexp.MustCompile(`type (\w+) struct\s*\{\s*(?:exprBase|stmtBase)`)

func main() { os.Exit(run("ast.go", "kinds.go", os.Stderr)) }

// run generates kindsPath from the node types declared in astPath.
func run(astPath, kindsPath string, stderr io.Writer) int {
	if err := generate(astPath, kindsPath); err != nil {
		fmt.Fprintln(stderr, "genkinds:", err)
		return 1
	}
	return 0
}

func generate(astPath, kindsPath string) error {
	src, err := os.ReadFile(astPath)
	if err != nil {
		return err
	}
	var names []string
	for _, m := range nodeRe.FindAllSubmatch(src, -1) {
		names = append(names, string(m[1]))
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by tools/genkinds from ast.go; DO NOT EDIT.\n\npackage syntax\n\n")
	b.WriteString("// NodeKind identifies the concrete type of a node (used for rule dispatch).\ntype NodeKind uint8\n\nconst (\n\tKindInvalid NodeKind = iota\n")
	for _, n := range names {
		fmt.Fprintf(&b, "\tK%s\n", n)
	}
	b.WriteString("\tNumNodeKinds\n)\n\n")
	for _, n := range names {
		fmt.Fprintf(&b, "func (*%s) Kind() NodeKind { return K%s }\n", n, n)
	}
	b.WriteString("\nvar nodeKindNames = [...]string{\n\tKindInvalid: \"Invalid\",\n")
	for _, n := range names {
		fmt.Fprintf(&b, "\tK%s: %q,\n", n, n)
	}
	b.WriteString("}\n\nfunc (k NodeKind) String() string {\n\tif int(k) < len(nodeKindNames) {\n\t\treturn nodeKindNames[k]\n\t}\n\treturn \"NodeKind(?)\"\n}\n")
	out, err := format.Source(b.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile(kindsPath, out, 0o644)
}
