// Command rulesdoc regenerates docs/rules.md: the migration status of every
// rule (spec written, EA conformance result from the last local run).
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"

	"custos/internal/meta"
)

const (
	out        = "docs/rules.md"
	statusFile = ".cache/ea/conformance.json"
)

func main() {
	rules, err := meta.All()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	status := map[string]string{}
	if b, err := os.ReadFile(statusFile); err == nil {
		_ = json.Unmarshal(b, &status)
	}
	// Keep the last known status of rules not run this time (e.g. RULE= runs).
	prev := previousStatus()
	for id, s := range prev {
		if _, ok := status[id]; !ok {
			status[id] = s
		}
	}

	byGroup := map[string][]meta.Rule{}
	var groups []string
	specs, pass := 0, 0
	for _, r := range rules {
		if _, ok := byGroup[r.Group]; !ok {
			groups = append(groups, r.Group)
		}
		byGroup[r.Group] = append(byGroup[r.Group], r)
		if hasSpec(r.ID) {
			specs++
		}
		if status[r.ID] == "pass" {
			pass++
		}
	}
	sort.Strings(groups)

	var b strings.Builder
	b.WriteString("# Rule migration status\n\n")
	b.WriteString("Generated by `make rules-doc` — do not edit by hand.\n\n")
	fmt.Fprintf(&b, "- Rules: **%d**\n- Specs written: **%d/%d**\n- EA conformance passing: **%d/%d**\n\n", len(rules), specs, len(rules), pass, len(rules))
	b.WriteString("Conformance: `pass` / `fail` / `pending` (not implemented) / `—` (not run).\n")
	for _, g := range groups {
		fmt.Fprintf(&b, "\n## %s\n\n| Rule | Severity | Default | Fix | Spec | EA conformance |\n| :--- | :--- | :---: | :---: | :---: | :---: |\n", g)
		for _, r := range byGroup[g] {
			def := yes(r.EnabledByDefault)
			if r.Experimental {
				def = "exp."
			}
			st := status[r.ID]
			if st == "" {
				st = "—"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s |\n", r.ID, r.Severity, def, yes(r.HasFix), yes(hasSpec(r.ID)), st)
		}
	}
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("%s: %d rules, %d specs, %d passing\n", out, len(rules), specs, pass)
}

func hasSpec(id string) bool {
	_, err := os.Stat("specs/" + id + ".md")
	return err == nil
}

func yes(b bool) string {
	if b {
		return "✓"
	}
	return ""
}

// previousStatus parses the conformance column of the current docs/rules.md.
func previousStatus() map[string]string {
	m := map[string]string{}
	b, err := os.ReadFile(out)
	if err != nil {
		return m
	}
	for _, line := range strings.Split(string(b), "\n") {
		cols := strings.Split(line, "|")
		if len(cols) < 8 || !strings.HasPrefix(strings.TrimSpace(cols[1]), "`") {
			continue
		}
		id := strings.Trim(strings.TrimSpace(cols[1]), "`")
		if s := strings.TrimSpace(cols[6]); s != "—" && s != "" {
			m[id] = s
		}
	}
	return m
}
