package main

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"custos/internal/diagnostic"
	"custos/internal/inspection/meta"
)

func write(t *testing.T, path, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

func fake(t *testing.T, rules []meta.Rule, err error) {
	t.Helper()
	old := catalogue
	catalogue = func() ([]meta.Rule, error) { return rules, err }
	t.Cleanup(func() { catalogue = old })
}

func TestRun(t *testing.T) {
	fake(t, []meta.Rule{
		{ID: "Kettle", Group: "Kitchen", Severity: diagnostic.SeverityWarning, EnabledByDefault: true, HasFix: true},
		{ID: "Toaster", Group: "Kitchen", Severity: diagnostic.SeverityError, Experimental: true},
		{ID: "Lamp", Group: "Bedroom", Severity: diagnostic.SeverityInfo},
		{ID: "Clock", Group: "Bedroom", Severity: diagnostic.SeverityInfo},
		{ID: "Shelf", Group: "Attic", Severity: diagnostic.SeverityWarning, EnabledByDefault: true},
	}, nil)
	root := t.TempDir()
	write(t, filepath.Join(root, "specs/Kettle.md"), "# Kettle\n")
	write(t, filepath.Join(root, "specs/Lamp.md"), "# Lamp\n")
	// This run: Kettle passes, Lamp fails.
	write(t, filepath.Join(root, statusFile), `{"Kettle": "pass", "Lamp": "fail"}`)
	// Previous document: Lamp's old status is superseded, Clock's is kept,
	// Shelf's "—" and Toaster's blank cell mean "not run".
	write(t, filepath.Join(root, out), strings.Join([]string{
		"# old",
		"| Rule | Severity | Default | Fix | Spec | EA conformance |",
		"| :--- | :--- | :---: | :---: | :---: | :---: |",
		"| `Lamp` | info |  |  | ✓ | pass |",
		"| `Clock` | info |  |  |  | pending |",
		"| `Shelf` | warning | ✓ |  |  | — |",
		"| `Toaster` | error | exp. |  |  |  |",
		"| short | row |",
	}, "\n"))

	var stdout, stderr bytes.Buffer
	if code := run(root, &stdout, &stderr); code != 0 {
		t.Fatalf("exit %d: %s", code, stderr.String())
	}
	if got := stdout.String(); got != "docs/internals/rules.md: 5 rules, 2 specs, 1 passing\n" {
		t.Errorf("stdout = %q", got)
	}
	doc, err := os.ReadFile(filepath.Join(root, out))
	if err != nil {
		t.Fatal(err)
	}
	want := `# Rule status

Generated by ` + "`make rules-doc`" + ` — do not edit by hand.

- Rules: **5**
- Specs written: **2/5**
- EA conformance passing: **1/5**

Conformance: ` + "`pass` / `fail` / `pending` (not implemented) / `—` (not run)." + `

## Attic

| Rule | Severity | Default | Fix | Spec | EA conformance |
| :--- | :--- | :---: | :---: | :---: | :---: |
| ` + "`Shelf`" + ` | warning | ✓ |  |  | — |

## Bedroom

| Rule | Severity | Default | Fix | Spec | EA conformance |
| :--- | :--- | :---: | :---: | :---: | :---: |
| ` + "`Lamp`" + ` | info |  |  | ✓ | fail |
| ` + "`Clock`" + ` | info |  |  |  | pending |

## Kitchen

| Rule | Severity | Default | Fix | Spec | EA conformance |
| :--- | :--- | :---: | :---: | :---: | :---: |
| ` + "`Kettle`" + ` | warning | ✓ | ✓ | ✓ | pass |
| ` + "`Toaster`" + ` | error | exp. |  |  | — |
`
	if string(doc) != want {
		t.Errorf("got:\n%s\nwant:\n%s", doc, want)
	}
}

func TestRunNoHistory(t *testing.T) {
	fake(t, []meta.Rule{{ID: "Vase", Group: "Hall", Severity: diagnostic.SeverityInfo}}, nil)
	root := t.TempDir()
	write(t, filepath.Join(root, "docs/internals/.keep"), "")
	var stdout, stderr bytes.Buffer
	if code := run(root, &stdout, &stderr); code != 0 {
		t.Fatalf("exit %d: %s", code, stderr.String())
	}
	doc, _ := os.ReadFile(filepath.Join(root, out))
	if !strings.Contains(string(doc), "| `Vase` | info |  |  |  | — |") {
		t.Errorf("got:\n%s", doc)
	}
}

func TestRunErrors(t *testing.T) {
	var stdout, stderr bytes.Buffer
	fake(t, nil, errors.New("catalogue broken"))
	if code := run(t.TempDir(), &stdout, &stderr); code != 1 || stderr.String() != "catalogue broken\n" {
		t.Fatalf("catalogue error: exit %d, %q", code, stderr.String())
	}
	// No docs/internals/ directory to write into.
	fake(t, nil, nil)
	stderr.Reset()
	if code := run(t.TempDir(), &stdout, &stderr); code != 1 || stderr.Len() == 0 {
		t.Fatalf("write error: exit %d, %q", code, stderr.String())
	}
}

func TestNativeConformance(t *testing.T) {
	fake(t, []meta.Rule{{ID: "Original", Native: true, Group: "Native", Severity: diagnostic.SeverityWarning}, {ID: "Ported", Group: "Native", Severity: diagnostic.SeverityWarning}}, nil)
	root := t.TempDir()
	write(t, filepath.Join(root, out), "")
	write(t, filepath.Join(root, statusFile), `{"Original":"pass","Ported":"pass"}`)
	var stdout, stderr bytes.Buffer
	if code := run(root, &stdout, &stderr); code != 0 {
		t.Fatal(stderr.String())
	}
	body, err := os.ReadFile(filepath.Join(root, out))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"EA conformance passing: **1/1**", "| `Original` | warning |  |  |  | N/A |", "no upstream counterpart"} {
		if !strings.Contains(string(body), want) {
			t.Errorf("missing %q in %s", want, body)
		}
	}
}
