<?php
class Tokens
{
    public function salt()
    {
        $raw = <error descr="Pass a second argument to learn whether a strong algorithm was used.">openssl_random_pseudo_bytes</error>(16);
        if (false === $raw) {
            throw new RuntimeException('no entropy');
        }
        return $raw;
    }

    public function nonce()
    {
        $n = mcrypt_create_iv(24, <error descr="Prefer MCRYPT_DEV_RANDOM as the entropy source.">MCRYPT_RAND</error>);
        return $n !== false ? $n : null;
    }

    public function pepper()
    {
        return <error descr="The generated bytes may be false; check the result.">openssl_random_pseudo_bytes</error>(8, <error descr="The strength flag may be false; check it.">$strong</error>);
    }

    public function seed()
    {
        $bytes = @openssl_random_pseudo_bytes(32, $good);
        if (!$bytes || !$good) {
            return null;
        }
        return $bytes;
    }

    public function iv()
    {
        $iv = <error descr="Pass the entropy source explicitly; its default differs between PHP versions."><error descr="The generated bytes may be false; check the result.">mcrypt_create_iv</error></error>(16);
        return $iv;
    }
}
