<?php
class Entropy
{
    public function forms($f)
    {
        $x = $f(16);
        $y = <error descr="The generated bytes may be false; check the result.">openssl_random_pseudo_bytes</error>(16, ...);
        [$a] = openssl_random_pseudo_bytes(16, <error descr="The strength flag may be false; check it.">$s</error>);
        $b = <error descr="The generated bytes may be false; check the result.">openssl_random_pseudo_bytes</error>(16, $ok);
        if ($ok === \false) {
            return null;
        }
        return [$x, $y, $a, $b];
    }
}

interface Source
{
    // Not valid PHP (a default must be a constant expression): the call has
    // no enclosing body to search for false checks.
    public function make($seed = <error descr="The generated bytes may be false; check the result.">openssl_random_pseudo_bytes</error>(8, $strong));
}
