package cryptographicallysecurerandomness

import (
	"custos/internal/diagnostic"
	"custos/internal/inspection/analysis"
	"custos/internal/inspection/astquery"
	"custos/internal/php/syntax"
	phpversion "custos/internal/php/version"
)

// cryptographicallySecureRandomness reports risky uses of
// openssl_random_pseudo_bytes() and mcrypt_create_iv().
type cryptographicallySecureRandomness struct{}

func (cryptographicallySecureRandomness) ID() string { return "CryptographicallySecureRandomness" }
func (cryptographicallySecureRandomness) Kinds() []syntax.NodeKind {
	return []syntax.NodeKind{syntax.KFuncCall}
}

func (cryptographicallySecureRandomness) Check(ctx *analysis.Context, n syntax.Node) {
	call := n.(*syntax.FuncCall)
	name, ok := call.Name.(*syntax.Name)
	if !ok || call.Args == nil {
		return
	}
	fn := ctx.GlobalFunctionName(call)
	openssl := fn == "openssl_random_pseudo_bytes"
	if !openssl && fn != "mcrypt_create_iv" {
		return
	}
	args := call.Args.Args
	if len(args) != 1 && len(args) != 2 { // E1
		return
	}
	nameSpan := astquery.NamePartSpan(name)
	if ctx.PHP.AtLeast(phpversion.PHP70) { // D1
		ctx.ReportSeverity(nameSpan, diagnostic.SeverityInfo, "Use random_bytes() for cryptographically secure randomness.")
	}
	// custos: from PHP 7.4 openssl_random_pseudo_bytes() throws instead of
	// using a weak source, so the strength flag is always true (D2, D5).
	modern := openssl && ctx.PHP.AtLeast(phpversion.PHP74)
	if len(args) == 1 && !modern { // D2
		if openssl {
			ctx.Report(nameSpan, "Pass a second argument to learn whether a strong algorithm was used.")
		} else {
			ctx.Report(nameSpan, "Pass the entropy source explicitly; its default differs between PHP versions.")
		}
	}
	if ctx.PHP.Below(phpversion.PHP74) && !resultVerified(ctx, call) { // D3
		ctx.Report(nameSpan, "The generated bytes may be false; check the result.")
	}
	if len(args) != 2 {
		return
	}
	second := astquery.ArgValue(args[1])
	if second == nil {
		return
	}
	if !openssl { // D4
		if c, ok := second.(*syntax.ConstFetch); ok && c.Name != nil && astquery.LastNamePart(c.Name.Value) != "MCRYPT_DEV_RANDOM" {
			ctx.ReportNode(second, "Prefer MCRYPT_DEV_RANDOM as the entropy source.")
		}
		return
	}
	if !modern && second.Span().Len() > 0 && !flagChecked(ctx.File, second) { // D5
		ctx.ReportNode(second, "The strength flag may be false; check it.")
	}
}

// resultVerified implements D3: the call result is assigned to a target
// that is false-checked (or to no recognisable target).
func resultVerified(ctx *analysis.Context, call *syntax.FuncCall) bool {
	p := call.Parent()
	if u, ok := p.(*syntax.Unary); ok && u.Op.Kind == syntax.TAt {
		p = u.Parent()
	}
	a, ok := p.(*syntax.Assign)
	if !ok {
		return false
	}
	switch a.Var.(type) {
	case nil, *syntax.Array, *syntax.List:
		return true
	}
	return falseChecked(ctx.File, a.Var)
}

// falseChecked reports whether s is compared with `=== false`/`!== false`
// or negated anywhere in its enclosing function body.
func falseChecked(f *syntax.File, s syntax.Node) bool {
	fn := syntax.EnclosingFuncLike(s)
	if fn == nil {
		return true
	}
	body := syntax.FuncLikeBody(fn)
	if body == nil {
		return true
	}
	found := false
	syntax.Inspect(body, func(n syntax.Node) bool {
		if found {
			return false
		}
		switch x := n.(type) {
		case *syntax.Binary:
			if x.Op.Kind == syntax.TIsIdentical || x.Op.Kind == syntax.TIsNotIdentical {
				if isFalse(x.Left) && astquery.EquivalentFoldNames(f, x.Right, s) || isFalse(x.Right) && astquery.EquivalentFoldNames(f, x.Left, s) {
					found = true
				}
			}
		case *syntax.Unary:
			if x.Op.Kind == syntax.TExclaim && astquery.EquivalentFoldNames(f, x.Expr, s) {
				found = true
			}
		}
		return !found
	})
	return found
}

// flagChecked is falseChecked for the D5 strength flag, a plain bool: a
// truthiness test (a condition or logical operand, `$strong ? … : …`) or a
// loose `==`/`!=` comparison with true or false checks it as well
// (custos diverges).
func flagChecked(f *syntax.File, s syntax.Node) bool {
	if falseChecked(f, s) {
		return true
	}
	found := false
	var body syntax.Node // nil for arrow functions (FuncLikeBody's nil *Block must not be walked)
	if b := syntax.FuncLikeBody(syntax.EnclosingFuncLike(s)); b != nil {
		body = b
	}
	syntax.Inspect(body, func(n syntax.Node) bool {
		if found {
			return false
		}
		if x, ok := n.(*syntax.Binary); ok && (x.Op.Kind == syntax.TIsEqual || x.Op.Kind == syntax.TIsNotEqual) {
			if isBoolConst(x.Left) && astquery.EquivalentFoldNames(f, x.Right, s) || isBoolConst(x.Right) && astquery.EquivalentFoldNames(f, x.Left, s) {
				found = true
			}
		}
		if e, ok := n.(syntax.Expr); ok && n != s && astquery.IsLogicalOperand(n) && astquery.EquivalentFoldNames(f, e, s) {
			found = true
		}
		return !found
	})
	return found
}

func isBoolConst(e syntax.Expr) bool {
	_, ok := astquery.BoolConst(e)
	return ok
}

func isFalse(e syntax.Expr) bool {
	c, ok := e.(*syntax.ConstFetch)
	if !ok || c.Name == nil {
		return false
	}
	v := c.Name.Value
	if v != "" && v[0] == '\\' {
		v = v[1:]
	}
	return len(v) == 5 && (v[0]|0x20) == 'f' && (v[1]|0x20) == 'a' && (v[2]|0x20) == 'l' && (v[3]|0x20) == 's' && (v[4]|0x20) == 'e'
}
