// Code generated by tools/genkinds from ast.go; DO NOT EDIT.

package syntax

// NodeKind identifies the concrete type of a node (used for rule dispatch).
type NodeKind uint8

const (
	KindInvalid NodeKind = iota
	KName
	KIdentifier
	KVariable
	KArrayDimFetch
	KPropertyFetch
	KStaticPropertyFetch
	KClassConstFetch
	KConstFetch
	KArg
	KVariadicPlaceholder
	KArgList
	KFuncCall
	KMethodCall
	KStaticCall
	KNew
	KAssign
	KBinary
	KUnary
	KIncDec
	KTernary
	KInstanceof
	KIsset
	KEmpty
	KExit
	KPrint
	KInclude
	KEval
	KClone
	KThrow
	KYield
	KYieldFrom
	KArrayItem
	KArray
	KList
	KClosureUse
	KClosure
	KArrowFunction
	KMatchArm
	KMatch
	KLiteral
	KStringPart
	KInterpolatedString
	KMagicConst
	KParen
	KBadExpr
	KNullableType
	KUnionType
	KIntersectionType
	KAttribute
	KAttributeGroup
	KPropertyHook
	KParam
	KBlock
	KExprStmt
	KEcho
	KInlineHTML
	KNop
	KIf
	KElseIf
	KElse
	KWhile
	KDoWhile
	KFor
	KForeach
	KCase
	KSwitch
	KBreak
	KContinue
	KReturn
	KGlobal
	KStaticVar
	KStaticStmt
	KUnset
	KGoto
	KLabel
	KCatch
	KFinally
	KTry
	KDeclareItem
	KDeclare
	KHaltCompiler
	KUseItem
	KUse
	KNamespace
	KConstItem
	KConstStmt
	KFunction
	KClassLike
	KMethod
	KPropertyItem
	KProperty
	KClassConst
	KEnumCase
	KTraitAdaptation
	KTraitUse
	KBadStmt
	NumNodeKinds
)

func (*Name) Kind() NodeKind                { return KName }
func (*Identifier) Kind() NodeKind          { return KIdentifier }
func (*Variable) Kind() NodeKind            { return KVariable }
func (*ArrayDimFetch) Kind() NodeKind       { return KArrayDimFetch }
func (*PropertyFetch) Kind() NodeKind       { return KPropertyFetch }
func (*StaticPropertyFetch) Kind() NodeKind { return KStaticPropertyFetch }
func (*ClassConstFetch) Kind() NodeKind     { return KClassConstFetch }
func (*ConstFetch) Kind() NodeKind          { return KConstFetch }
func (*Arg) Kind() NodeKind                 { return KArg }
func (*VariadicPlaceholder) Kind() NodeKind { return KVariadicPlaceholder }
func (*ArgList) Kind() NodeKind             { return KArgList }
func (*FuncCall) Kind() NodeKind            { return KFuncCall }
func (*MethodCall) Kind() NodeKind          { return KMethodCall }
func (*StaticCall) Kind() NodeKind          { return KStaticCall }
func (*New) Kind() NodeKind                 { return KNew }
func (*Assign) Kind() NodeKind              { return KAssign }
func (*Binary) Kind() NodeKind              { return KBinary }
func (*Unary) Kind() NodeKind               { return KUnary }
func (*IncDec) Kind() NodeKind              { return KIncDec }
func (*Ternary) Kind() NodeKind             { return KTernary }
func (*Instanceof) Kind() NodeKind          { return KInstanceof }
func (*Isset) Kind() NodeKind               { return KIsset }
func (*Empty) Kind() NodeKind               { return KEmpty }
func (*Exit) Kind() NodeKind                { return KExit }
func (*Print) Kind() NodeKind               { return KPrint }
func (*Include) Kind() NodeKind             { return KInclude }
func (*Eval) Kind() NodeKind                { return KEval }
func (*Clone) Kind() NodeKind               { return KClone }
func (*Throw) Kind() NodeKind               { return KThrow }
func (*Yield) Kind() NodeKind               { return KYield }
func (*YieldFrom) Kind() NodeKind           { return KYieldFrom }
func (*ArrayItem) Kind() NodeKind           { return KArrayItem }
func (*Array) Kind() NodeKind               { return KArray }
func (*List) Kind() NodeKind                { return KList }
func (*ClosureUse) Kind() NodeKind          { return KClosureUse }
func (*Closure) Kind() NodeKind             { return KClosure }
func (*ArrowFunction) Kind() NodeKind       { return KArrowFunction }
func (*MatchArm) Kind() NodeKind            { return KMatchArm }
func (*Match) Kind() NodeKind               { return KMatch }
func (*Literal) Kind() NodeKind             { return KLiteral }
func (*StringPart) Kind() NodeKind          { return KStringPart }
func (*InterpolatedString) Kind() NodeKind  { return KInterpolatedString }
func (*MagicConst) Kind() NodeKind          { return KMagicConst }
func (*Paren) Kind() NodeKind               { return KParen }
func (*BadExpr) Kind() NodeKind             { return KBadExpr }
func (*NullableType) Kind() NodeKind        { return KNullableType }
func (*UnionType) Kind() NodeKind           { return KUnionType }
func (*IntersectionType) Kind() NodeKind    { return KIntersectionType }
func (*Attribute) Kind() NodeKind           { return KAttribute }
func (*AttributeGroup) Kind() NodeKind      { return KAttributeGroup }
func (*PropertyHook) Kind() NodeKind        { return KPropertyHook }
func (*Param) Kind() NodeKind               { return KParam }
func (*Block) Kind() NodeKind               { return KBlock }
func (*ExprStmt) Kind() NodeKind            { return KExprStmt }
func (*Echo) Kind() NodeKind                { return KEcho }
func (*InlineHTML) Kind() NodeKind          { return KInlineHTML }
func (*Nop) Kind() NodeKind                 { return KNop }
func (*If) Kind() NodeKind                  { return KIf }
func (*ElseIf) Kind() NodeKind              { return KElseIf }
func (*Else) Kind() NodeKind                { return KElse }
func (*While) Kind() NodeKind               { return KWhile }
func (*DoWhile) Kind() NodeKind             { return KDoWhile }
func (*For) Kind() NodeKind                 { return KFor }
func (*Foreach) Kind() NodeKind             { return KForeach }
func (*Case) Kind() NodeKind                { return KCase }
func (*Switch) Kind() NodeKind              { return KSwitch }
func (*Break) Kind() NodeKind               { return KBreak }
func (*Continue) Kind() NodeKind            { return KContinue }
func (*Return) Kind() NodeKind              { return KReturn }
func (*Global) Kind() NodeKind              { return KGlobal }
func (*StaticVar) Kind() NodeKind           { return KStaticVar }
func (*StaticStmt) Kind() NodeKind          { return KStaticStmt }
func (*Unset) Kind() NodeKind               { return KUnset }
func (*Goto) Kind() NodeKind                { return KGoto }
func (*Label) Kind() NodeKind               { return KLabel }
func (*Catch) Kind() NodeKind               { return KCatch }
func (*Finally) Kind() NodeKind             { return KFinally }
func (*Try) Kind() NodeKind                 { return KTry }
func (*DeclareItem) Kind() NodeKind         { return KDeclareItem }
func (*Declare) Kind() NodeKind             { return KDeclare }
func (*HaltCompiler) Kind() NodeKind        { return KHaltCompiler }
func (*UseItem) Kind() NodeKind             { return KUseItem }
func (*Use) Kind() NodeKind                 { return KUse }
func (*Namespace) Kind() NodeKind           { return KNamespace }
func (*ConstItem) Kind() NodeKind           { return KConstItem }
func (*ConstStmt) Kind() NodeKind           { return KConstStmt }
func (*Function) Kind() NodeKind            { return KFunction }
func (*ClassLike) Kind() NodeKind           { return KClassLike }
func (*Method) Kind() NodeKind              { return KMethod }
func (*PropertyItem) Kind() NodeKind        { return KPropertyItem }
func (*Property) Kind() NodeKind            { return KProperty }
func (*ClassConst) Kind() NodeKind          { return KClassConst }
func (*EnumCase) Kind() NodeKind            { return KEnumCase }
func (*TraitAdaptation) Kind() NodeKind     { return KTraitAdaptation }
func (*TraitUse) Kind() NodeKind            { return KTraitUse }
func (*BadStmt) Kind() NodeKind             { return KBadStmt }

var nodeKindNames = [...]string{
	KindInvalid:          "Invalid",
	KName:                "Name",
	KIdentifier:          "Identifier",
	KVariable:            "Variable",
	KArrayDimFetch:       "ArrayDimFetch",
	KPropertyFetch:       "PropertyFetch",
	KStaticPropertyFetch: "StaticPropertyFetch",
	KClassConstFetch:     "ClassConstFetch",
	KConstFetch:          "ConstFetch",
	KArg:                 "Arg",
	KVariadicPlaceholder: "VariadicPlaceholder",
	KArgList:             "ArgList",
	KFuncCall:            "FuncCall",
	KMethodCall:          "MethodCall",
	KStaticCall:          "StaticCall",
	KNew:                 "New",
	KAssign:              "Assign",
	KBinary:              "Binary",
	KUnary:               "Unary",
	KIncDec:              "IncDec",
	KTernary:             "Ternary",
	KInstanceof:          "Instanceof",
	KIsset:               "Isset",
	KEmpty:               "Empty",
	KExit:                "Exit",
	KPrint:               "Print",
	KInclude:             "Include",
	KEval:                "Eval",
	KClone:               "Clone",
	KThrow:               "Throw",
	KYield:               "Yield",
	KYieldFrom:           "YieldFrom",
	KArrayItem:           "ArrayItem",
	KArray:               "Array",
	KList:                "List",
	KClosureUse:          "ClosureUse",
	KClosure:             "Closure",
	KArrowFunction:       "ArrowFunction",
	KMatchArm:            "MatchArm",
	KMatch:               "Match",
	KLiteral:             "Literal",
	KStringPart:          "StringPart",
	KInterpolatedString:  "InterpolatedString",
	KMagicConst:          "MagicConst",
	KParen:               "Paren",
	KBadExpr:             "BadExpr",
	KNullableType:        "NullableType",
	KUnionType:           "UnionType",
	KIntersectionType:    "IntersectionType",
	KAttribute:           "Attribute",
	KAttributeGroup:      "AttributeGroup",
	KPropertyHook:        "PropertyHook",
	KParam:               "Param",
	KBlock:               "Block",
	KExprStmt:            "ExprStmt",
	KEcho:                "Echo",
	KInlineHTML:          "InlineHTML",
	KNop:                 "Nop",
	KIf:                  "If",
	KElseIf:              "ElseIf",
	KElse:                "Else",
	KWhile:               "While",
	KDoWhile:             "DoWhile",
	KFor:                 "For",
	KForeach:             "Foreach",
	KCase:                "Case",
	KSwitch:              "Switch",
	KBreak:               "Break",
	KContinue:            "Continue",
	KReturn:              "Return",
	KGlobal:              "Global",
	KStaticVar:           "StaticVar",
	KStaticStmt:          "StaticStmt",
	KUnset:               "Unset",
	KGoto:                "Goto",
	KLabel:               "Label",
	KCatch:               "Catch",
	KFinally:             "Finally",
	KTry:                 "Try",
	KDeclareItem:         "DeclareItem",
	KDeclare:             "Declare",
	KHaltCompiler:        "HaltCompiler",
	KUseItem:             "UseItem",
	KUse:                 "Use",
	KNamespace:           "Namespace",
	KConstItem:           "ConstItem",
	KConstStmt:           "ConstStmt",
	KFunction:            "Function",
	KClassLike:           "ClassLike",
	KMethod:              "Method",
	KPropertyItem:        "PropertyItem",
	KProperty:            "Property",
	KClassConst:          "ClassConst",
	KEnumCase:            "EnumCase",
	KTraitAdaptation:     "TraitAdaptation",
	KTraitUse:            "TraitUse",
	KBadStmt:             "BadStmt",
}

func (k NodeKind) String() string {
	if int(k) < len(nodeKindNames) {
		return nodeKindNames[k]
	}
	return "NodeKind(?)"
}
