package main

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"testing"

	"custos/internal/meta"
)

func fake(t *testing.T, rules []meta.Rule, err error, descs map[string]meta.Description) {
	t.Helper()
	oc, od := catalogue, describe
	catalogue = func() ([]meta.Rule, error) { return rules, err }
	describe = func(id string) (meta.Description, bool) { d, ok := descs[id]; return d, ok }
	t.Cleanup(func() { catalogue, describe = oc, od })
}

func TestRun(t *testing.T) {
	fake(t, []meta.Rule{
		{ID: "Kettle", LegacyID: "KettleInspection", Group: "Hot Drinks", Severity: meta.SeverityWarning, EnabledByDefault: true},
		{ID: "Toaster", LegacyID: "ToasterInspection", Group: "Hot Drinks", Severity: meta.SeverityError, Experimental: true},
		{ID: "Lamp", LegacyID: "LampInspection", Group: "Bedroom", Severity: meta.SeverityInfo},
		{ID: "Clock", LegacyID: "ClockInspection", Group: "Bedroom", Severity: meta.SeverityInfo, EnabledByDefault: true},
	}, nil, map[string]meta.Description{
		"Kettle":  {Summary: "Kettles should whistle once.", Options: "- `PITCH` (int, default 3)", Fix: true},
		"Toaster": {Summary: "Toast evenly."},
		"Lamp":    {Options: "- `DIM` (bool)"},
	})
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "docs"), 0o755); err != nil {
		t.Fatal(err)
	}
	var stdout, stderr bytes.Buffer
	if code := run(root, &stdout, &stderr); code != 0 {
		t.Fatalf("exit %d: %s", code, stderr.String())
	}
	if got := stdout.String(); got != "docs/rules-reference.md: 4 rules in 2 groups\n" {
		t.Errorf("stdout = %q", got)
	}
	doc, err := os.ReadFile(filepath.Join(root, out))
	if err != nil {
		t.Fatal(err)
	}
	want := "# Rule reference\n\nGenerated by `make rules-doc` from the rule catalogue and specs — do not edit by hand.\n" +
		"Run `custos explain <rule>` for the same text in the terminal. Rule IDs also accept the PhpStorm\n" +
		"inspection name (`<ID>Inspection`), e.g. in `@noinspection` comments and `custos.json`.\n\n" +
		"- [Bedroom](#bedroom) (2)\n- [Hot Drinks](#hot-drinks) (2)\n" +
		"\n## Bedroom\n" +
		"\n### Lamp\n\n`LampInspection` · severity **info** · default **off** · quick-fix **no**\n\n" +
		"\n**Options**\n\n- `DIM` (bool)\n" +
		"\n### Clock\n\n`ClockInspection` · severity **info** · default **on** · quick-fix **no**\n\n" +
		"\n## Hot Drinks\n" +
		"\n### Kettle\n\n`KettleInspection` · severity **warning** · default **on** · quick-fix **yes**\n\n" +
		"Kettles should whistle once.\n\n**Options**\n\n- `PITCH` (int, default 3)\n" +
		"\n### Toaster\n\n`ToasterInspection` · severity **error** · default **off, experimental** · quick-fix **no**\n\n" +
		"Toast evenly.\n"
	if string(doc) != want {
		t.Errorf("got:\n%s\nwant:\n%s", doc, want)
	}
}

func TestRunErrors(t *testing.T) {
	var stdout, stderr bytes.Buffer
	fake(t, nil, errors.New("catalogue broken"), nil)
	if code := run(t.TempDir(), &stdout, &stderr); code != 1 || stderr.String() != "catalogue broken\n" {
		t.Fatalf("catalogue error: exit %d, %q", code, stderr.String())
	}
	fake(t, nil, nil, nil)
	stderr.Reset()
	if code := run(t.TempDir(), &stdout, &stderr); code != 1 || stderr.Len() == 0 {
		t.Fatalf("write error: exit %d, %q", code, stderr.String())
	}
}
