// Command rulesref generates the rule reference of the documentation site:
// docs/rules/index.md, one page per rule (docs/rules/<group>/<ID>.md) and
// the VitePress sidebar (docs/.vitepress/rules-sidebar.json), from
// internal/inspection/meta and the specs' own text and examples.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"html"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"custos/internal/diagnostic"
	"custos/internal/inspection/meta"
	"custos/internal/testing/conformance"
	"custos/tools/internal/specmd"
)

const (
	outDir  = "docs/rules"
	sidebar = "docs/.vitepress/rules-sidebar.json"
)

// Seams for tests: the catalogue and the descriptions are embedded.
var (
	catalogue = meta.All
	describe  = meta.Describe
)

func main() { os.Exit(run(".", os.Stdout, os.Stderr)) }

type sideItem struct {
	Text      string     `json:"text"`
	Link      string     `json:"link,omitempty"`
	Collapsed *bool      `json:"collapsed,omitempty"`
	Items     []sideItem `json:"items,omitempty"`
}

// run rewrites root/docs/rules (removing pages of rules that no longer
// exist) and root/docs/.vitepress/rules-sidebar.json.
func run(root string, stdout, stderr io.Writer) int {
	rules, err := catalogue()
	if err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}
	byGroup := map[string][]meta.Rule{}
	var groups []string
	for _, r := range rules {
		if _, ok := byGroup[r.Group]; !ok {
			groups = append(groups, r.Group)
		}
		byGroup[r.Group] = append(byGroup[r.Group], r)
	}
	sort.Strings(groups)

	files := map[string]string{} // path relative to root → content
	var index strings.Builder
	index.WriteString("---\ntitle: Rules\n---\n\n<!-- Generated by `make rules-doc` — do not edit by hand. -->\n\n# Rules\n\n")
	fmt.Fprintf(&index, "custos ships **%d rules** in %d groups. Rules marked *off* only run when enabled in\n", len(rules), len(groups))
	index.WriteString("[`custos.json`](/guide/configuration) or with `--all`; rules with a quick-fix are applied by `custos fix`\n")
	index.WriteString("and offered as code actions by the language server. Every rule also answers to its PhpStorm\n")
	index.WriteString("inspection name (`<ID>Inspection`), in `@noinspection` comments, `--rule` and `custos.json`.\n")
	collapsed := true
	var side []sideItem
	for _, g := range groups {
		slug := anchor(g)
		fmt.Fprintf(&index, "\n## %s\n\n| Rule | Severity | Default | Quick-fix | PHP |\n| :--- | :--- | :---: | :---: | :--- |\n", g)
		group := sideItem{Text: g, Collapsed: &collapsed}
		for _, r := range byGroup[g] {
			md := readSpec(root, r.ID)
			d, _ := describe(r.ID)
			fmt.Fprintf(&index, "| [%s](./%s/%s) | %s | %s | %s | %s |\n", r.ID, slug, r.ID, r.Severity, onOff(r), yes(d.Fix), phpRange(md, "any"))
			group.Items = append(group.Items, sideItem{Text: r.ID, Link: "/rules/" + slug + "/" + r.ID})
			files[filepath.Join(outDir, slug, r.ID+".md")] = page(r, slug, d, md)
		}
		side = append(side, group)
	}
	files[filepath.Join(outDir, "index.md")] = index.String()
	b, _ := json.MarshalIndent(side, "", "  ")
	files[sidebar] = string(b) + "\n"

	if err := os.RemoveAll(filepath.Join(root, outDir)); err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}
	paths := make([]string, 0, len(files))
	for p := range files {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		full := filepath.Join(root, p)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			fmt.Fprintln(stderr, err)
			return 1
		}
		if err := os.WriteFile(full, []byte(files[p]), 0o644); err != nil {
			fmt.Fprintln(stderr, err)
			return 1
		}
	}
	fmt.Fprintf(stdout, "%s: %d rules in %d groups\n", outDir, len(rules), len(groups))
	return 0
}

// readSpec returns specs/<id>.md, or "" when the rule has none.
func readSpec(root, id string) string {
	b, _ := os.ReadFile(filepath.Join(root, "specs", id+".md"))
	return string(b)
}

var severityBadge = map[diagnostic.Severity]string{
	diagnostic.SeverityError:   "danger",
	diagnostic.SeverityWarning: "warning",
	diagnostic.SeverityInfo:    "info",
}

func page(r meta.Rule, slug string, d meta.Description, md string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "---\ntitle: %s\n---\n\n<!-- Generated by `make rules-doc` from specs/%s.md — do not edit by hand. -->\n\n", r.ID, r.ID)
	fmt.Fprintf(&b, "# %s\n\n", r.ID)
	badges := []string{`<Badge type="` + severityBadge[r.Severity] + `" text="` + string(r.Severity) + `" />`}
	if r.EnabledByDefault {
		badges = append(badges, `<Badge type="tip" text="on by default" />`)
	} else {
		badges = append(badges, `<Badge type="info" text="off by default" />`)
	}
	if r.Experimental {
		badges = append(badges, `<Badge type="warning" text="experimental" />`)
	}
	if d.Fix {
		badges = append(badges, `<Badge type="tip" text="quick-fix" />`)
	}
	if p := phpRange(md, ""); p != "" {
		badges = append(badges, `<Badge type="info" text="`+p+`" />`)
	}
	b.WriteString(strings.Join(badges, " "))
	fmt.Fprintf(&b, "\n\nGroup: [%s](/rules/#%s) · PhpStorm name: `%s`\n", r.Group, slug, r.LegacyID)
	if d.Summary != "" {
		b.WriteString("\n" + d.Summary + "\n")
	}
	example(&b, md, d.Fix)
	if d.Options != "" {
		b.WriteString("\n## Options\n\n" + d.Options + "\n")
	}
	configure(&b, r)
	fmt.Fprintf(&b, "\n## Suppress\n\nBefore the statement or declaration (or the first statement of the file), either of:\n\n```php\n// @custos-ignore %s\n\n/**\n * @noinspection %s\n */\n```\n", r.ID, r.LegacyID)
	return b.String()
}

// example renders the spec's first example with the flagged lines
// highlighted and, when the block right after it is the quick-fix output,
// a Before / After tab pair.
func example(b *strings.Builder, md string, fix bool) {
	blocks := specmd.Blocks(specmd.Section(md, "Examples"))
	if len(blocks) == 0 || blocks[0].Lang != "php" {
		return
	}
	clean, exps, err := conformance.ParseMarkup([]byte(blocks[0].Body))
	if err != nil || len(exps) == 0 {
		return
	}
	var lines []string
	seen := map[int]bool{}
	var msgs []string
	for _, e := range exps {
		first := bytes.Count(clean[:e.Start], []byte("\n")) + 1
		last := bytes.Count(clean[:e.End], []byte("\n")) + 1
		for l := first; l <= last; l++ {
			if !seen[l] {
				seen[l] = true
				lines = append(lines, fmt.Sprint(l))
			}
		}
		if m := fmt.Sprintf("<li>line %d: %s</li>", first, escape(e.Message)); e.Message != "" && (len(msgs) == 0 || msgs[len(msgs)-1] != m) {
			msgs = append(msgs, m)
		}
	}
	marks := "{" + strings.Join(lines, ",") + "}"
	b.WriteString("\n## Example\n\n")
	if blocks[0].Prose != "" {
		b.WriteString(blocks[0].Prose + "\n\n")
	}
	after := ""
	if fix && len(blocks) > 1 && blocks[1].Prose == "" && blocks[1].Lang == "php" && !strings.Contains(blocks[1].Body, "descr=\"") && blocks[1].Body != string(clean) {
		after = blocks[1].Body
	}
	if after == "" {
		fmt.Fprintf(b, "```php%s\n%s```\n", marks, clean)
	} else {
		fmt.Fprintf(b, "::: code-group\n\n```php%s [Before]\n%s```\n\n```php [After fix]\n%s```\n\n:::\n", marks, clean, after)
	}
	if len(msgs) > 0 {
		b.WriteString("\nReported:\n\n<ul>\n" + strings.Join(msgs, "\n") + "\n</ul>\n")
	}
}

// configure shows the custos.json entry that flips the rule's default,
// with its options at their default values.
func configure(b *strings.Builder, r meta.Rule) {
	var opts []string
	for _, o := range r.Options {
		v := o.Default
		if v == nil && o.Type == "list" {
			v = []string{}
		}
		if v == nil {
			continue
		}
		j, _ := json.Marshal(v)
		opts = append(opts, fmt.Sprintf("        %q: %s", o.Name, j))
	}
	fmt.Fprintf(b, "\n## Configure\n\nIn [`custos.json`](/guide/configuration):\n\n```json\n{\n  \"rules\": {\n    %q: {\n      \"enabled\": %t", r.ID, !r.EnabledByDefault)
	if len(opts) > 0 {
		b.WriteString(",\n      \"options\": {\n" + strings.Join(opts, ",\n") + "\n      }")
	}
	b.WriteString("\n    }\n  }\n}\n```\n")
}

// phpRange describes the target PHP versions of a spec's front matter, or
// returns none when the rule is not version-gated.
func phpRange(md, none string) string {
	min, max := specmd.PHP(md)
	switch {
	case min != "" && max != "":
		return "PHP " + min + "–" + max
	case min != "":
		return "PHP ≥ " + min
	case max != "":
		return "PHP ≤ " + max
	}
	return none
}

// escape makes a message safe as page text: HTML-escaped, and with braces
// that the page's Vue template would otherwise read as interpolation.
func escape(s string) string {
	return strings.NewReplacer("{", "&#123;", "}", "&#125;").Replace(html.EscapeString(s))
}

func onOff(r meta.Rule) string {
	s := "off"
	if r.EnabledByDefault {
		s = "on"
	}
	if r.Experimental {
		s += ", experimental"
	}
	return s
}

func yes(b bool) string {
	if b {
		return "✓"
	}
	return ""
}

func anchor(s string) string {
	return strings.ToLower(strings.ReplaceAll(s, " ", "-"))
}
