// Command rulesref generates docs/rules-reference.md: the user-facing
// reference of every rule (group, severity, default, fix, summary, options)
// from internal/meta and the specs' own summaries.
package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"custos/internal/meta"
)

const out = "docs/rules-reference.md"

// Seams for tests: the catalogue and the descriptions are embedded.
var (
	catalogue = meta.All
	describe  = meta.Describe
)

func main() { os.Exit(run(".", os.Stdout, os.Stderr)) }

// run writes root/docs/rules-reference.md.
func run(root string, stdout, stderr io.Writer) int {
	rules, err := catalogue()
	if err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}
	byGroup := map[string][]meta.Rule{}
	var groups []string
	for _, r := range rules {
		if _, ok := byGroup[r.Group]; !ok {
			groups = append(groups, r.Group)
		}
		byGroup[r.Group] = append(byGroup[r.Group], r)
	}
	sort.Strings(groups)

	var b strings.Builder
	b.WriteString("# Rule reference\n\nGenerated by `make rules-doc` from the rule catalogue and specs — do not edit by hand.\n")
	b.WriteString("Run `custos explain <rule>` for the same text in the terminal. Rule IDs also accept the PhpStorm\n")
	b.WriteString("inspection name (`<ID>Inspection`), e.g. in `@noinspection` comments and `custos.json`.\n\n")
	for _, g := range groups {
		fmt.Fprintf(&b, "- [%s](#%s) (%d)\n", g, anchor(g), len(byGroup[g]))
	}
	for _, g := range groups {
		fmt.Fprintf(&b, "\n## %s\n", g)
		for _, r := range byGroup[g] {
			def := "on"
			if !r.EnabledByDefault {
				def = "off"
			}
			if r.Experimental {
				def += ", experimental"
			}
			// What custos actually offers: a rule has quick-fixes when its own
			// fixtures include an expected fix output (*.fixed.*).
			d, ok := describe(r.ID)
			fix := "no"
			if ok && d.Fix {
				fix = "yes"
			}
			fmt.Fprintf(&b, "\n### %s\n\n`%s` · severity **%s** · default **%s** · quick-fix **%s**\n\n", r.ID, r.LegacyID, r.Severity, def, fix)
			if ok {
				if d.Summary != "" {
					b.WriteString(d.Summary + "\n")
				}
				if d.Options != "" {
					b.WriteString("\n**Options**\n\n" + d.Options + "\n")
				}
			}
		}
	}
	if err := os.WriteFile(filepath.Join(root, out), []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}
	fmt.Fprintf(stdout, "%s: %d rules in %d groups\n", out, len(rules), len(groups))
	return 0
}

func anchor(s string) string {
	return strings.ToLower(strings.ReplaceAll(s, " ", "-"))
}
