// Package meta holds the catalogue of rule facts: identifiers, groups,
// default severities and option schemas. The catalogue is generated by
// tools/extract and contains facts only — never descriptions or messages.
package meta

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"sort"
	"sync"

	"custos/internal/diagnostic"
)

// Option describes one configurable rule option.
type Option struct {
	Name    string `json:"name"`
	Type    string `json:"type"` // bool | int | string | enum | list
	Default any    `json:"default,omitempty"`
}

// Rule is the fact sheet of one rule.
type Rule struct {
	ID               string              `json:"id"`
	LegacyID         string              `json:"legacyId"` // PhpStorm short name, honoured by @noinspection
	Group            string              `json:"group"`
	Severity         diagnostic.Severity `json:"severity"`
	EnabledByDefault bool                `json:"enabledByDefault"`
	HasFix           bool                `json:"hasFix"`
	Experimental     bool                `json:"experimental,omitempty"` // disabled upstream; off by default
	Options          []Option            `json:"options,omitempty"`
}

//go:embed rules.json
var rulesJSON []byte

var (
	loadOnce sync.Once
	rules    []Rule
	byID     map[string]*Rule
	loadErr  error
)

func load() {
	if err := json.Unmarshal(rulesJSON, &rules); err != nil {
		loadErr = fmt.Errorf("meta: decode rules.json: %w", err)
		return
	}
	sort.Slice(rules, func(i, j int) bool { return rules[i].ID < rules[j].ID })
	byID = make(map[string]*Rule, len(rules)*2)
	for i := range rules {
		byID[rules[i].ID] = &rules[i]
		byID[rules[i].LegacyID] = &rules[i]
	}
}

// All returns every rule, sorted by ID.
func All() ([]Rule, error) {
	loadOnce.Do(load)
	return rules, loadErr
}

// Lookup finds a rule by custos ID or legacy PhpStorm short name.
func Lookup(id string) (*Rule, bool) {
	loadOnce.Do(load)
	r, ok := byID[id]
	return r, ok
}
